SET( HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( HAVE_CLOCK_MONOTONIC_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)
SET( HAVE_CLOCK_REALTIME_EXITCODE
     0
     CACHE STRING "Result from TRY_RUN" FORCE)
