//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Threading.Tasks.Parallel.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Partitioner source returned a null enumerator..
        /// </summary>
        internal static string Parallel_ForEach_NullEnumerator {
            get {
                return ResourceManager.GetString("Parallel_ForEach_NullEnumerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method requires the use of an OrderedPartitioner with the KeysNormalized property set to true..
        /// </summary>
        internal static string Parallel_ForEach_OrderedPartitionerKeysNotNormalized {
            get {
                return ResourceManager.GetString("Parallel_ForEach_OrderedPartitionerKeysNotNormalized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Partitioner used here must support dynamic partitioning..
        /// </summary>
        internal static string Parallel_ForEach_PartitionerNotDynamic {
            get {
                return ResourceManager.GetString("Parallel_ForEach_PartitionerNotDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Partitioner used here returned a null partitioner source..
        /// </summary>
        internal static string Parallel_ForEach_PartitionerReturnedNull {
            get {
                return ResourceManager.GetString("Parallel_ForEach_PartitionerReturnedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the actions was null..
        /// </summary>
        internal static string Parallel_Invoke_ActionNull {
            get {
                return ResourceManager.GetString("Parallel_Invoke_ActionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break was called after Stop was called..
        /// </summary>
        internal static string ParallelState_Break_InvalidOperationException_BreakAfterStop {
            get {
                return ResourceManager.GetString("ParallelState_Break_InvalidOperationException_BreakAfterStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This method is not supported..
        /// </summary>
        internal static string ParallelState_NotSupportedException_UnsupportedMethod {
            get {
                return ResourceManager.GetString("ParallelState_NotSupportedException_UnsupportedMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop was called after Break was called..
        /// </summary>
        internal static string ParallelState_Stop_InvalidOperationException_StopAfterBreak {
            get {
                return ResourceManager.GetString("ParallelState_Stop_InvalidOperationException_StopAfterBreak", resourceCulture);
            }
        }
    }
}
