//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration yielded no results.
        /// </summary>
        internal static string EmptyEnumerable {
            get {
                return ResourceManager.GetString("EmptyEnumerable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains more than one element.
        /// </summary>
        internal static string MoreThanOneElement {
            get {
                return ResourceManager.GetString("MoreThanOneElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains more than one matching element.
        /// </summary>
        internal static string MoreThanOneMatch {
            get {
                return ResourceManager.GetString("MoreThanOneMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains no elements.
        /// </summary>
        internal static string NoElements {
            get {
                return ResourceManager.GetString("NoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence contains no matching element.
        /// </summary>
        internal static string NoMatch {
            get {
                return ResourceManager.GetString("NoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The second data source of a binary operator must be of type System.Linq.ParallelQuery&lt;T&gt; rather than System.Collections.Generic.IEnumerable&lt;T&gt;. To fix this problem, use the AsParallel() extension method to convert the right data source to System.Linq.ParallelQuery&lt;T&gt;..
        /// </summary>
        internal static string ParallelEnumerable_BinaryOpMustUseAsParallel {
            get {
                return ResourceManager.GetString("ParallelEnumerable_BinaryOpMustUseAsParallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CancellationTokenSource associated with this CancellationToken has been disposed..
        /// </summary>
        internal static string ParallelEnumerable_WithCancellation_TokenSourceDisposed {
            get {
                return ResourceManager.GetString("ParallelEnumerable_WithCancellation_TokenSourceDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mergeOptions argument contains an invalid value..
        /// </summary>
        internal static string ParallelEnumerable_WithMergeOptions_InvalidOptions {
            get {
                return ResourceManager.GetString("ParallelEnumerable_WithMergeOptions_InvalidOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The executionMode argument contains an invalid value..
        /// </summary>
        internal static string ParallelEnumerable_WithQueryExecutionMode_InvalidMode {
            get {
                return ResourceManager.GetString("ParallelEnumerable_WithQueryExecutionMode_InvalidMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned array&apos;s length must equal the number of partitions requested..
        /// </summary>
        internal static string ParallelPartitionable_IncorretElementCount {
            get {
                return ResourceManager.GetString("ParallelPartitionable_IncorretElementCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements returned must not be null..
        /// </summary>
        internal static string ParallelPartitionable_NullElement {
            get {
                return ResourceManager.GetString("ParallelPartitionable_NullElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return value must not be null..
        /// </summary>
        internal static string ParallelPartitionable_NullReturn {
            get {
                return ResourceManager.GetString("ParallelPartitionable_NullReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WithDegreeOfParallelism operator may be used at most once in a query..
        /// </summary>
        internal static string ParallelQuery_DuplicateDOP {
            get {
                return ResourceManager.GetString("ParallelQuery_DuplicateDOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WithExecutionMode operator may be used at most once in a query..
        /// </summary>
        internal static string ParallelQuery_DuplicateExecutionMode {
            get {
                return ResourceManager.GetString("ParallelQuery_DuplicateExecutionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WithMergeOptions operator may be used at most once in a query..
        /// </summary>
        internal static string ParallelQuery_DuplicateMergeOptions {
            get {
                return ResourceManager.GetString("ParallelQuery_DuplicateMergeOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WithTaskScheduler operator may be used at most once in a query..
        /// </summary>
        internal static string ParallelQuery_DuplicateTaskScheduler {
            get {
                return ResourceManager.GetString("ParallelQuery_DuplicateTaskScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WithCancellation operator may by used at most once in a query..
        /// </summary>
        internal static string ParallelQuery_DuplicateWithCancellation {
            get {
                return ResourceManager.GetString("ParallelQuery_DuplicateWithCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsOrdered may only be called on the result of AsParallel, ParallelEnumerable.Range, or ParallelEnumerable.Repeat..
        /// </summary>
        internal static string ParallelQuery_InvalidAsOrderedCall {
            get {
                return ResourceManager.GetString("ParallelQuery_InvalidAsOrderedCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-generic AsOrdered may only be called on the result of the non-generic AsParallel..
        /// </summary>
        internal static string ParallelQuery_InvalidNonGenericAsOrderedCall {
            get {
                return ResourceManager.GetString("ParallelQuery_InvalidNonGenericAsOrderedCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsOrdered may not be used with a partitioner that is not orderable..
        /// </summary>
        internal static string ParallelQuery_PartitionerNotOrderable {
            get {
                return ResourceManager.GetString("ParallelQuery_PartitionerNotOrderable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitioner returned a null partition..
        /// </summary>
        internal static string PartitionerQueryOperator_NullPartition {
            get {
                return ResourceManager.GetString("PartitionerQueryOperator_NullPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitioner returned null instead of a list of partitions..
        /// </summary>
        internal static string PartitionerQueryOperator_NullPartitionList {
            get {
                return ResourceManager.GetString("PartitionerQueryOperator_NullPartitionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitioner returned a wrong number of partitions..
        /// </summary>
        internal static string PartitionerQueryOperator_WrongNumberOfPartitions {
            get {
                return ResourceManager.GetString("PartitionerQueryOperator_WrongNumberOfPartitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration has not started. MoveNext must be called to initiate enumeration..
        /// </summary>
        internal static string PLINQ_CommonEnumerator_Current_NotStarted {
            get {
                return ResourceManager.GetString("PLINQ_CommonEnumerator_Current_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query enumerator has been disposed..
        /// </summary>
        internal static string PLINQ_DisposeRequested {
            get {
                return ResourceManager.GetString("PLINQ_DisposeRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query enumerator previously threw an exception..
        /// </summary>
        internal static string PLINQ_EnumerationPreviouslyFailed {
            get {
                return ResourceManager.GetString("PLINQ_EnumerationPreviouslyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The query has been canceled via the token supplied to WithCancellation..
        /// </summary>
        internal static string PLINQ_ExternalCancellationRequested {
            get {
                return ResourceManager.GetString("PLINQ_ExternalCancellationRequested", resourceCulture);
            }
        }
    }
}
