//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Win32.Registry.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One machine may not have remote administration enabled, or both machines may not be running the remote registry service..
        /// </summary>
        internal static string Arg_DllInitFailure {
            get {
                return ResourceManager.GetString("Arg_DllInitFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal enum value: {0}..
        /// </summary>
        internal static string Arg_EnumIllegalVal {
            get {
                return ResourceManager.GetString("Arg_EnumIllegalVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified RegistryValueKind is an invalid value..
        /// </summary>
        internal static string Arg_RegBadKeyKind {
            get {
                return ResourceManager.GetString("Arg_RegBadKeyKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryKey.GetValue does not allow a String that has a length greater than Int32.MaxValue..
        /// </summary>
        internal static string Arg_RegGetOverflowBug {
            get {
                return ResourceManager.GetString("Arg_RegGetOverflowBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key name must start with a valid base key name..
        /// </summary>
        internal static string Arg_RegInvalidKeyName {
            get {
                return ResourceManager.GetString("Arg_RegInvalidKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a registry hive&apos;s subtree..
        /// </summary>
        internal static string Arg_RegKeyDelHive {
            get {
                return ResourceManager.GetString("Arg_RegKeyDelHive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No remote connection to &apos;{0}&apos; while trying to read the registry..
        /// </summary>
        internal static string Arg_RegKeyNoRemoteConnect {
            get {
                return ResourceManager.GetString("Arg_RegKeyNoRemoteConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified registry key does not exist..
        /// </summary>
        internal static string Arg_RegKeyNotFound {
            get {
                return ResourceManager.GetString("Arg_RegKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry HKEY was out of the legal range..
        /// </summary>
        internal static string Arg_RegKeyOutOfRange {
            get {
                return ResourceManager.GetString("Arg_RegKeyOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key names should not be greater than 255 characters..
        /// </summary>
        internal static string Arg_RegKeyStrLenBug {
            get {
                return ResourceManager.GetString("Arg_RegKeyStrLenBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryKey.SetValue does not support arrays of type &apos;{0}&apos;. Only Byte[] and String[] are supported..
        /// </summary>
        internal static string Arg_RegSetBadArrType {
            get {
                return ResourceManager.GetString("Arg_RegSetBadArrType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the value object did not match the specified RegistryValueKind or the object could not be properly converted..
        /// </summary>
        internal static string Arg_RegSetMismatchedKind {
            get {
                return ResourceManager.GetString("Arg_RegSetMismatchedKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegistryKey.SetValue does not allow a String[] that contains a null String reference..
        /// </summary>
        internal static string Arg_RegSetStrArrNull {
            get {
                return ResourceManager.GetString("Arg_RegSetStrArrNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a subkey tree because the subkey does not exist..
        /// </summary>
        internal static string Arg_RegSubKeyAbsent {
            get {
                return ResourceManager.GetString("Arg_RegSubKeyAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value exists with that name..
        /// </summary>
        internal static string Arg_RegSubKeyValueAbsent {
            get {
                return ResourceManager.GetString("Arg_RegSubKeyValueAbsent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry value names should not be greater than 16,383 characters..
        /// </summary>
        internal static string Arg_RegValStrLenBug {
            get {
                return ResourceManager.GetString("Arg_RegValStrLenBug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified RegistryKeyPermissionCheck value is invalid..
        /// </summary>
        internal static string Argument_InvalidRegistryKeyPermissionCheck {
            get {
                return ResourceManager.GetString("Argument_InvalidRegistryKeyPermissionCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified RegistryOptions value is invalid..
        /// </summary>
        internal static string Argument_InvalidRegistryOptionsCheck {
            get {
                return ResourceManager.GetString("Argument_InvalidRegistryOptionsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified RegistryView value is invalid..
        /// </summary>
        internal static string Argument_InvalidRegistryViewCheck {
            get {
                return ResourceManager.GetString("Argument_InvalidRegistryViewCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key has subkeys and recursive removes are not supported by this method..
        /// </summary>
        internal static string InvalidOperation_RegRemoveSubKey {
            get {
                return ResourceManager.GetString("InvalidOperation_RegRemoveSubKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed registry key..
        /// </summary>
        internal static string ObjectDisposed_RegKeyClosed {
            get {
                return ResourceManager.GetString("ObjectDisposed_RegKeyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested registry access is not allowed..
        /// </summary>
        internal static string Security_RegistryPermission {
            get {
                return ResourceManager.GetString("Security_RegistryPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to the registry key &apos;{0}&apos; is denied..
        /// </summary>
        internal static string UnauthorizedAccess_RegistryKeyGeneric_Key {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_RegistryKeyGeneric_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the registry key..
        /// </summary>
        internal static string UnauthorizedAccess_RegistryNoWrite {
            get {
                return ResourceManager.GetString("UnauthorizedAccess_RegistryNoWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownError_Num {
            get {
                return ResourceManager.GetString("UnknownError_Num", resourceCulture);
            }
        }
    }
}
