# Disable triggers for now. TODO: add right merge triggers.
trigger: none

# TODO: add paths to exclude CI when modifying docs or stuff not affecting the build
pr:
- master

resources:
  containers:
  - container: rhel7_container
    image: microsoft/dotnet-buildtools-prereqs:rhel7_prereqs_2

  - container: alpine_36_container
    image: microsoft/dotnet-buildtools-prereqs:alpine-3.6-WithNode-dc92048-20181204212646

  - container: ubuntu_1604_arm64_cross_container
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921

  - container: ubuntu_1604_arm_cross_container
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-ef0ac75-20175511035548

jobs:
  # Windows legs
  - template: /eng/pipelines/windows.yml

  # Linux legs
  - template: /eng/pipelines/linux.yml

  # MacOS legs
  - template: /eng/pipelines/macos.yml
