# Setting batch to true, triggers one build at a time.
# if there is a push while a build in progress, it will wait,
# until the running build finishes, and produce a build with all the changes
# that happened during the last build.
trigger:
  batch: true
  branches:
    include:
    - master
    - release/3.0
  paths:
    exclude:
    - Documentation/*
    - /*.md

pr:
  branches:
    include:
    - master
    - release/3.0
  paths:
    exclude:
    - Documentation/*
    - /*.md

variables:
  - name: _isOfficialBuild
    value: ${{ and(ne(variables['System.TeamProject'], 'public'), notIn(variables['Build.Reason'], 'PullRequest')) }}
  - name: _fullMatrix
    value: ${{ notIn(variables['Build.Reason'], 'PullRequest') }}

resources:
  containers:
  - container: rhel7_container
    image: microsoft/dotnet-buildtools-prereqs:rhel7_prereqs_2

  - container: rhel6_container
    image: microsoft/dotnet-buildtools-prereqs:centos-6-376e1a3-20174311014331

  - container: alpine_36_container
    image: microsoft/dotnet-buildtools-prereqs:alpine-3.6-WithNode-f4d3fe3-20181213005010

  - container: alpine_37_arm64_container
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-alpine10fcdcf-20190208200917

  - container: ubuntu_1604_arm64_cross_container
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921

  - container: ubuntu_1604_arm_cross_container
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-ef0ac75-20175511035548

jobs:
  # Windows legs
  - template: /eng/pipelines/windows.yml
    parameters:
      isOfficialBuild: $(_isOfficialBuild)
      fullMatrix: $(_fullMatrix)

  # Linux legs
  - template: /eng/pipelines/linux.yml
    parameters:
      isOfficialBuild: $(_isOfficialBuild)
      fullMatrix: $(_fullMatrix)

  # MacOS legs
  - template: /eng/pipelines/macos.yml
    parameters:
      isOfficialBuild: $(_isOfficialBuild)
      fullMatrix: $(_fullMatrix)

  # RedHat6 leg
  - template: /eng/pipelines/redhat6.yml
    parameters:
      isOfficialBuild: $(_isOfficialBuild)
      fullMatrix: $(_fullMatrix)

    # FreeBSD leg is only for official builds
    # - template: /eng/pipelines/freebsd.yml
    #   parameters:
    #     isOfficialBuild: true
    #     fullMatrix: false

    # Publish step
    - template: /eng/pipelines/publish.yml
      parameters:
        dependsOn:
          - WindowsTest
          - WindowsNoTest
          - AllConfigurations
          - LinuxTest
          - MacOS
          - RedHat6
          # - FreeBSD
