# https://docs.codecov.io/docs/codecov-yaml
# https://github.com/codecov/support/wiki/Codecov-Yaml

coverage:
  status:
    project:
      default: false
    patch:
      default: false

comment:
  layout: "reach, diff, files"
  require_changes: yes