' Do not edit this file manually it is auto-generated during the build based on the .resx file for this project.
Namespace System
    Friend Partial Class SR
    
        Private Const s_resourcesName As String = "Microsoft.VisualBasic.resources" ' assembly Name + .resources

#If Not DEBUGRESOURCES Then
        Friend Shared ReadOnly Property ID91 As String
           Get
                 Return SR.GetResourceString("ID91", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ID92 As String
           Get
                 Return SR.GetResourceString("ID92", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_GEZero1 As String
           Get
                 Return SR.GetResourceString("Argument_GEZero1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_GTZero1 As String
           Get
                 Return SR.GetResourceString("Argument_GTZero1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_LengthGTZero1 As String
           Get
                 Return SR.GetResourceString("Argument_LengthGTZero1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_RangeTwoBytes1 As String
           Get
                 Return SR.GetResourceString("Argument_RangeTwoBytes1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_MinusOneOrGTZero1 As String
           Get
                 Return SR.GetResourceString("Argument_MinusOneOrGTZero1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_GEMinusOne1 As String
           Get
                 Return SR.GetResourceString("Argument_GEMinusOne1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_GEOne1 As String
           Get
                 Return SR.GetResourceString("Argument_GEOne1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_RankEQOne1 As String
           Get
                 Return SR.GetResourceString("Argument_RankEQOne1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_IComparable2 As String
           Get
                 Return SR.GetResourceString("Argument_IComparable2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_NotNumericType2 As String
           Get
                 Return SR.GetResourceString("Argument_NotNumericType2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidValue1 As String
           Get
                 Return SR.GetResourceString("Argument_InvalidValue1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidValueType2 As String
           Get
                 Return SR.GetResourceString("Argument_InvalidValueType2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidValue As String
           Get
                 Return SR.GetResourceString("Argument_InvalidValue", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Collection_BeforeAfterExclusive As String
           Get
                 Return SR.GetResourceString("Collection_BeforeAfterExclusive", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Collection_DuplicateKey As String
           Get
                 Return SR.GetResourceString("Collection_DuplicateKey", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_CommonType2 As String
           Get
                 Return SR.GetResourceString("ForLoop_CommonType2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_CommonType3 As String
           Get
                 Return SR.GetResourceString("ForLoop_CommonType3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_ConvertToType3 As String
           Get
                 Return SR.GetResourceString("ForLoop_ConvertToType3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_OperatorRequired2 As String
           Get
                 Return SR.GetResourceString("ForLoop_OperatorRequired2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_UnacceptableOperator2 As String
           Get
                 Return SR.GetResourceString("ForLoop_UnacceptableOperator2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_UnacceptableRelOperator2 As String
           Get
                 Return SR.GetResourceString("ForLoop_UnacceptableRelOperator2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property InternalError As String
           Get
                 Return SR.GetResourceString("InternalError", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property MaxErrNumber As String
           Get
                 Return SR.GetResourceString("MaxErrNumber", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidNullValue1 As String
           Get
                 Return SR.GetResourceString("Argument_InvalidNullValue1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidRank1 As String
           Get
                 Return SR.GetResourceString("Argument_InvalidRank1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_Range0to99_1 As String
           Get
                 Return SR.GetResourceString("Argument_Range0to99_1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Array_RankMismatch As String
           Get
                 Return SR.GetResourceString("Array_RankMismatch", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Array_TypeMismatch As String
           Get
                 Return SR.GetResourceString("Array_TypeMismatch", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property InvalidCast_FromTo As String
           Get
                 Return SR.GetResourceString("InvalidCast_FromTo", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property InvalidCast_FromStringTo As String
           Get
                 Return SR.GetResourceString("InvalidCast_FromStringTo", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidDateValue1 As String
           Get
                 Return SR.GetResourceString("Argument_InvalidDateValue1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentNotNumeric1 As String
           Get
                 Return SR.GetResourceString("ArgumentNotNumeric1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_IndexLELength2 As String
           Get
                 Return SR.GetResourceString("Argument_IndexLELength2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property MissingMember_NoDefaultMemberFound1 As String
           Get
                 Return SR.GetResourceString("MissingMember_NoDefaultMemberFound1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property MissingMember_MemberNotFoundOnType2 As String
           Get
                 Return SR.GetResourceString("MissingMember_MemberNotFoundOnType2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property IntermediateLateBoundNothingResult1 As String
           Get
                 Return SR.GetResourceString("IntermediateLateBoundNothingResult1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_CollectionIndex As String
           Get
                 Return SR.GetResourceString("Argument_CollectionIndex", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property RValueBaseForValueType As String
           Get
                 Return SR.GetResourceString("RValueBaseForValueType", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ExpressionNotProcedure As String
           Get
                 Return SR.GetResourceString("ExpressionNotProcedure", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property LateboundCallToInheritedComClass As String
           Get
                 Return SR.GetResourceString("LateboundCallToInheritedComClass", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property MissingMember_ReadOnlyField2 As String
           Get
                 Return SR.GetResourceString("MissingMember_ReadOnlyField2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidNamedArgs As String
           Get
                 Return SR.GetResourceString("Argument_InvalidNamedArgs", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property SyncLockRequiresReferenceType1 As String
           Get
                 Return SR.GetResourceString("SyncLockRequiresReferenceType1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NullReference_InstanceReqToAccessMember1 As String
           Get
                 Return SR.GetResourceString("NullReference_InstanceReqToAccessMember1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property MatchArgumentFailure2 As String
           Get
                 Return SR.GetResourceString("MatchArgumentFailure2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoGetProperty1 As String
           Get
                 Return SR.GetResourceString("NoGetProperty1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoSetProperty1 As String
           Get
                 Return SR.GetResourceString("NoSetProperty1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property MethodAssignment1 As String
           Get
                 Return SR.GetResourceString("MethodAssignment1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoViableOverloadCandidates1 As String
           Get
                 Return SR.GetResourceString("NoViableOverloadCandidates1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoArgumentCountOverloadCandidates1 As String
           Get
                 Return SR.GetResourceString("NoArgumentCountOverloadCandidates1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoTypeArgumentCountOverloadCandidates1 As String
           Get
                 Return SR.GetResourceString("NoTypeArgumentCountOverloadCandidates1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoCallableOverloadCandidates2 As String
           Get
                 Return SR.GetResourceString("NoCallableOverloadCandidates2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoNonNarrowingOverloadCandidates2 As String
           Get
                 Return SR.GetResourceString("NoNonNarrowingOverloadCandidates2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoMostSpecificOverload2 As String
           Get
                 Return SR.GetResourceString("NoMostSpecificOverload2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property AmbiguousCast2 As String
           Get
                 Return SR.GetResourceString("AmbiguousCast2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NotMostSpecificOverload As String
           Get
                 Return SR.GetResourceString("NotMostSpecificOverload", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NamedParamNotFound2 As String
           Get
                 Return SR.GetResourceString("NamedParamNotFound2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NamedParamArrayArgument1 As String
           Get
                 Return SR.GetResourceString("NamedParamArrayArgument1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NamedArgUsedTwice2 As String
           Get
                 Return SR.GetResourceString("NamedArgUsedTwice2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property OmittedArgument1 As String
           Get
                 Return SR.GetResourceString("OmittedArgument1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property OmittedParamArrayArgument As String
           Get
                 Return SR.GetResourceString("OmittedParamArrayArgument", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentMismatch3 As String
           Get
                 Return SR.GetResourceString("ArgumentMismatch3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentMismatchAmbiguous3 As String
           Get
                 Return SR.GetResourceString("ArgumentMismatchAmbiguous3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentNarrowing3 As String
           Get
                 Return SR.GetResourceString("ArgumentNarrowing3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentMismatchCopyBack3 As String
           Get
                 Return SR.GetResourceString("ArgumentMismatchCopyBack3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentMismatchAmbiguousCopyBack3 As String
           Get
                 Return SR.GetResourceString("ArgumentMismatchAmbiguousCopyBack3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentNarrowingCopyBack3 As String
           Get
                 Return SR.GetResourceString("ArgumentNarrowingCopyBack3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property UnboundTypeParam1 As String
           Get
                 Return SR.GetResourceString("UnboundTypeParam1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property TypeInferenceFails1 As String
           Get
                 Return SR.GetResourceString("TypeInferenceFails1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property FailedTypeArgumentBinding As String
           Get
                 Return SR.GetResourceString("FailedTypeArgumentBinding", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property UnaryOperand2 As String
           Get
                 Return SR.GetResourceString("UnaryOperand2", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property BinaryOperands3 As String
           Get
                 Return SR.GetResourceString("BinaryOperands3", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoValidOperator_StringType1 As String
           Get
                 Return SR.GetResourceString("NoValidOperator_StringType1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property NoValidOperator_NonStringType1 As String
           Get
                 Return SR.GetResourceString("NoValidOperator_NonStringType1", Nothing)
            End Get
        End Property
        Friend Shared ReadOnly Property PropertySetMissingArgument1 As String
           Get
                 Return SR.GetResourceString("PropertySetMissingArgument1", Nothing)
            End Get
        End Property
#Else
        Friend Shared ReadOnly Property ID91 As String
            Get
                Return SR.GetResourceString("ID91", "Object variable or With block variable not set.")
            End Get
        End Property
        Friend Shared ReadOnly Property ID92 As String
            Get
                Return SR.GetResourceString("ID92", "For loop not initialized.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_GEZero1 As String
            Get
                Return SR.GetResourceString("Argument_GEZero1", "Argument '{0}' must be greater or equal to zero.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_GTZero1 As String
            Get
                Return SR.GetResourceString("Argument_GTZero1", "Argument '{0}' must be greater than zero.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_LengthGTZero1 As String
            Get
                Return SR.GetResourceString("Argument_LengthGTZero1", "Length of argument '{0}' must be greater than zero.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_RangeTwoBytes1 As String
            Get
                Return SR.GetResourceString("Argument_RangeTwoBytes1", "Argument '{0}' must be within the range of -32768 to 65535.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_MinusOneOrGTZero1 As String
            Get
                Return SR.GetResourceString("Argument_MinusOneOrGTZero1", "Argument '{0}' must be greater than 0 or equal to -1.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_GEMinusOne1 As String
            Get
                Return SR.GetResourceString("Argument_GEMinusOne1", "Argument '{0}' must be greater than or equal to -1.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_GEOne1 As String
            Get
                Return SR.GetResourceString("Argument_GEOne1", "Argument '{0}' must be greater than or equal to 1.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_RankEQOne1 As String
            Get
                Return SR.GetResourceString("Argument_RankEQOne1", "Argument '{0}' cannot be a multi-dimensional array.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_IComparable2 As String
            Get
                Return SR.GetResourceString("Argument_IComparable2", "Loop control variable of type '{1}' does not implement the 'System.IComparable' interface.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_NotNumericType2 As String
            Get
                Return SR.GetResourceString("Argument_NotNumericType2", "Type of argument '{0}' is '{1}', which is not numeric.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidValue1 As String
            Get
                Return SR.GetResourceString("Argument_InvalidValue1", "Argument '{0}' is not a valid value.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidValueType2 As String
            Get
                Return SR.GetResourceString("Argument_InvalidValueType2", "Argument '{0}' cannot be converted to type '{1}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidValue As String
            Get
                Return SR.GetResourceString("Argument_InvalidValue", "Arguments are not valid.")
            End Get
        End Property
        Friend Shared ReadOnly Property Collection_BeforeAfterExclusive As String
            Get
                Return SR.GetResourceString("Collection_BeforeAfterExclusive", "'Before' and 'After' arguments cannot be combined.")
            End Get
        End Property
        Friend Shared ReadOnly Property Collection_DuplicateKey As String
            Get
                Return SR.GetResourceString("Collection_DuplicateKey", "Add failed. Duplicate key value supplied.")
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_CommonType2 As String
            Get
                Return SR.GetResourceString("ForLoop_CommonType2", "Cannot convert start value of type '{0}' and step value of type '{1}' to a common numeric type.")
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_CommonType3 As String
            Get
                Return SR.GetResourceString("ForLoop_CommonType3", "Cannot convert start value of type '{0}', limit value of type '{1}', and step value of type '{2}' to a common numeric type.")
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_ConvertToType3 As String
            Get
                Return SR.GetResourceString("ForLoop_ConvertToType3", "Cannot convert argument '{0}' of type '{1}' to type '{2}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_OperatorRequired2 As String
            Get
                Return SR.GetResourceString("ForLoop_OperatorRequired2", "Type '{0}' must define an operator '{1}', with parameters of type '{0}', to be used in a 'For' statement.")
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_UnacceptableOperator2 As String
            Get
                Return SR.GetResourceString("ForLoop_UnacceptableOperator2", "Return and parameter types of '{0}' must be of type '{1}' to be used in a 'For' statement.")
            End Get
        End Property
        Friend Shared ReadOnly Property ForLoop_UnacceptableRelOperator2 As String
            Get
                Return SR.GetResourceString("ForLoop_UnacceptableRelOperator2", "Parameter types of '{0}' must be of type '{1}' to be used in a 'For' statement.")
            End Get
        End Property
        Friend Shared ReadOnly Property InternalError As String
            Get
                Return SR.GetResourceString("InternalError", "Internal error in the Microsoft Visual Basic runtime.")
            End Get
        End Property
        Friend Shared ReadOnly Property MaxErrNumber As String
            Get
                Return SR.GetResourceString("MaxErrNumber", "Error number must be within the range 0 to 65535.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidNullValue1 As String
            Get
                Return SR.GetResourceString("Argument_InvalidNullValue1", "Argument '{0}' is Nothing.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidRank1 As String
            Get
                Return SR.GetResourceString("Argument_InvalidRank1", "Argument '{0}' is not valid for the array.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_Range0to99_1 As String
            Get
                Return SR.GetResourceString("Argument_Range0to99_1", "Argument '{0}' must be within the range 0 to 99.")
            End Get
        End Property
        Friend Shared ReadOnly Property Array_RankMismatch As String
            Get
                Return SR.GetResourceString("Array_RankMismatch", "'ReDim' cannot change the number of dimensions.")
            End Get
        End Property
        Friend Shared ReadOnly Property Array_TypeMismatch As String
            Get
                Return SR.GetResourceString("Array_TypeMismatch", "'ReDim' can only change the rightmost dimension.")
            End Get
        End Property
        Friend Shared ReadOnly Property InvalidCast_FromTo As String
            Get
                Return SR.GetResourceString("InvalidCast_FromTo", "Conversion from type '{0}' to type '{1}' is not valid.")
            End Get
        End Property
        Friend Shared ReadOnly Property InvalidCast_FromStringTo As String
            Get
                Return SR.GetResourceString("InvalidCast_FromStringTo", "Conversion from string \""{0}\"" to type '{1}' is not valid.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidDateValue1 As String
            Get
                Return SR.GetResourceString("Argument_InvalidDateValue1", "Argument '{0}' cannot be converted to type 'Date'.")
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentNotNumeric1 As String
            Get
                Return SR.GetResourceString("ArgumentNotNumeric1", "Argument '{0}' cannot be converted to a numeric value.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_IndexLELength2 As String
            Get
                Return SR.GetResourceString("Argument_IndexLELength2", "Argument '{0}' must be less than or equal to the length of argument '{1}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property MissingMember_NoDefaultMemberFound1 As String
            Get
                Return SR.GetResourceString("MissingMember_NoDefaultMemberFound1", "No default member found for type '{0}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property MissingMember_MemberNotFoundOnType2 As String
            Get
                Return SR.GetResourceString("MissingMember_MemberNotFoundOnType2", "Public member '{0}' on type '{1}' not found.")
            End Get
        End Property
        Friend Shared ReadOnly Property IntermediateLateBoundNothingResult1 As String
            Get
                Return SR.GetResourceString("IntermediateLateBoundNothingResult1", "Invocation of '{0}' on type '{1}' returned Nothing.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_CollectionIndex As String
            Get
                Return SR.GetResourceString("Argument_CollectionIndex", "Collection index must be in the range 1 to the size of the collection.")
            End Get
        End Property
        Friend Shared ReadOnly Property RValueBaseForValueType As String
            Get
                Return SR.GetResourceString("RValueBaseForValueType", "Late-bound assignment to a field of value type '{0}' is not valid when '{1}' is the result of a late-bound expression.")
            End Get
        End Property
        Friend Shared ReadOnly Property ExpressionNotProcedure As String
            Get
                Return SR.GetResourceString("ExpressionNotProcedure", "Expression '{0}' is not a procedure, but occurs as the target of a procedure call.")
            End Get
        End Property
        Friend Shared ReadOnly Property LateboundCallToInheritedComClass As String
            Get
                Return SR.GetResourceString("LateboundCallToInheritedComClass", "Managed classes derived from a COM class cannot be called late bound.")
            End Get
        End Property
        Friend Shared ReadOnly Property MissingMember_ReadOnlyField2 As String
            Get
                Return SR.GetResourceString("MissingMember_ReadOnlyField2", "Field '{0}' of type '{1}' is 'ReadOnly'.")
            End Get
        End Property
        Friend Shared ReadOnly Property Argument_InvalidNamedArgs As String
            Get
                Return SR.GetResourceString("Argument_InvalidNamedArgs", "Named arguments are not valid as array subscripts.")
            End Get
        End Property
        Friend Shared ReadOnly Property SyncLockRequiresReferenceType1 As String
            Get
                Return SR.GetResourceString("SyncLockRequiresReferenceType1", "'SyncLock' operand cannot be of type '{0}' because '{0}' is not a reference type.")
            End Get
        End Property
        Friend Shared ReadOnly Property NullReference_InstanceReqToAccessMember1 As String
            Get
                Return SR.GetResourceString("NullReference_InstanceReqToAccessMember1", "Reference to non-shared member '{0}' requires an object reference.")
            End Get
        End Property
        Friend Shared ReadOnly Property MatchArgumentFailure2 As String
            Get
                Return SR.GetResourceString("MatchArgumentFailure2", "Method invocation failed because '{0}' cannot be called with these arguments:{1}")
            End Get
        End Property
        Friend Shared ReadOnly Property NoGetProperty1 As String
            Get
                Return SR.GetResourceString("NoGetProperty1", "Property '{0}' is WriteOnly.")
            End Get
        End Property
        Friend Shared ReadOnly Property NoSetProperty1 As String
            Get
                Return SR.GetResourceString("NoSetProperty1", "Property '{0}' is ReadOnly.")
            End Get
        End Property
        Friend Shared ReadOnly Property MethodAssignment1 As String
            Get
                Return SR.GetResourceString("MethodAssignment1", "Method '{0}' cannot be the target of an assignment.")
            End Get
        End Property
        Friend Shared ReadOnly Property NoViableOverloadCandidates1 As String
            Get
                Return SR.GetResourceString("NoViableOverloadCandidates1", "Overload resolution failed because no '{0}' is Public.")
            End Get
        End Property
        Friend Shared ReadOnly Property NoArgumentCountOverloadCandidates1 As String
            Get
                Return SR.GetResourceString("NoArgumentCountOverloadCandidates1", "Overload resolution failed because no accessible '{0}' accepts this number of arguments.")
            End Get
        End Property
        Friend Shared ReadOnly Property NoTypeArgumentCountOverloadCandidates1 As String
            Get
                Return SR.GetResourceString("NoTypeArgumentCountOverloadCandidates1", "Overload resolution failed because no accessible '{0}' accepts this number of type arguments.")
            End Get
        End Property
        Friend Shared ReadOnly Property NoCallableOverloadCandidates2 As String
            Get
                Return SR.GetResourceString("NoCallableOverloadCandidates2", "Overload resolution failed because no Public '{0}' can be called with these arguments:{1}")
            End Get
        End Property
        Friend Shared ReadOnly Property NoNonNarrowingOverloadCandidates2 As String
            Get
                Return SR.GetResourceString("NoNonNarrowingOverloadCandidates2", "Overload resolution failed because no Public '{0}' can be called without a narrowing conversion:{1}")
            End Get
        End Property
        Friend Shared ReadOnly Property NoMostSpecificOverload2 As String
            Get
                Return SR.GetResourceString("NoMostSpecificOverload2", "Overload resolution failed because no Public '{0}' is most specific for these arguments:{1}")
            End Get
        End Property
        Friend Shared ReadOnly Property AmbiguousCast2 As String
            Get
                Return SR.GetResourceString("AmbiguousCast2", "Conversion from type '{0}' to type '{1}' is ambiguous.")
            End Get
        End Property
        Friend Shared ReadOnly Property NotMostSpecificOverload As String
            Get
                Return SR.GetResourceString("NotMostSpecificOverload", "Not most specific.")
            End Get
        End Property
        Friend Shared ReadOnly Property NamedParamNotFound2 As String
            Get
                Return SR.GetResourceString("NamedParamNotFound2", "Named argument '{0}' matches no parameter of '{1}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property NamedParamArrayArgument1 As String
            Get
                Return SR.GetResourceString("NamedParamArrayArgument1", "Named argument '{0}' cannot match a ParamArray parameter.")
            End Get
        End Property
        Friend Shared ReadOnly Property NamedArgUsedTwice2 As String
            Get
                Return SR.GetResourceString("NamedArgUsedTwice2", "Parameter '{0}' of '{1}' already has a matching argument.")
            End Get
        End Property
        Friend Shared ReadOnly Property OmittedArgument1 As String
            Get
                Return SR.GetResourceString("OmittedArgument1", "Argument not specified for parameter '{0}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property OmittedParamArrayArgument As String
            Get
                Return SR.GetResourceString("OmittedParamArrayArgument", "Omitted argument cannot match a ParamArray parameter.")
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentMismatch3 As String
            Get
                Return SR.GetResourceString("ArgumentMismatch3", "Argument matching parameter '{0}' cannot convert from '{1}' to '{2}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentMismatchAmbiguous3 As String
            Get
                Return SR.GetResourceString("ArgumentMismatchAmbiguous3", "Argument matching parameter '{0}' cannot convert from '{1}' to '{2}' because the conversion is ambiguous.")
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentNarrowing3 As String
            Get
                Return SR.GetResourceString("ArgumentNarrowing3", "Argument matching parameter '{0}' narrows from '{1}' to '{2}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentMismatchCopyBack3 As String
            Get
                Return SR.GetResourceString("ArgumentMismatchCopyBack3", "ByRef parameter '{0}' cannot convert from '{1}' to '{2}' when assigning back to the matching argument.")
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentMismatchAmbiguousCopyBack3 As String
            Get
                Return SR.GetResourceString("ArgumentMismatchAmbiguousCopyBack3", "ByRef parameter '{0}' cannot convert from '{1}' to '{2}' when assigning back to the matching argument because the conversion is ambiguous.")
            End Get
        End Property
        Friend Shared ReadOnly Property ArgumentNarrowingCopyBack3 As String
            Get
                Return SR.GetResourceString("ArgumentNarrowingCopyBack3", "ByRef parameter '{0}' narrows from '{1}' to '{2}' when assigning back to the matching argument.")
            End Get
        End Property
        Friend Shared ReadOnly Property UnboundTypeParam1 As String
            Get
                Return SR.GetResourceString("UnboundTypeParam1", "Type parameter '{0}' cannot be determined.")
            End Get
        End Property
        Friend Shared ReadOnly Property TypeInferenceFails1 As String
            Get
                Return SR.GetResourceString("TypeInferenceFails1", "Type argument inference fails for argument matching parameter '{0}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property FailedTypeArgumentBinding As String
            Get
                Return SR.GetResourceString("FailedTypeArgumentBinding", "Substitution of type arguments failed.")
            End Get
        End Property
        Friend Shared ReadOnly Property UnaryOperand2 As String
            Get
                Return SR.GetResourceString("UnaryOperand2", "Operator '{0}' is not defined for type '{1}'.")
            End Get
        End Property
        Friend Shared ReadOnly Property BinaryOperands3 As String
            Get
                Return SR.GetResourceString("BinaryOperands3", "Operator '{0}' is not defined for {1} and {2}.")
            End Get
        End Property
        Friend Shared ReadOnly Property NoValidOperator_StringType1 As String
            Get
                Return SR.GetResourceString("NoValidOperator_StringType1", "string \""{0}\""")
            End Get
        End Property
        Friend Shared ReadOnly Property NoValidOperator_NonStringType1 As String
            Get
                Return SR.GetResourceString("NoValidOperator_NonStringType1", "type '{0}'")
            End Get
        End Property
        Friend Shared ReadOnly Property PropertySetMissingArgument1 As String
            Get
                Return SR.GetResourceString("PropertySetMissingArgument1", "Call to set property '{0}' requires at least one argument.")
            End Get
        End Property

#End If
    End Class
End Namespace
