// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.DataContractResolver))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.DataContractSerializer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.DataContractSerializerSettings))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.ExportOptions))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.ExtensionDataObject))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.IExtensibleDataObject))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.XmlObjectSerializer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.XmlSerializableServices))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.XPathQueryGenerator))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Runtime.Serialization.XsdDataContractExporter))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.IFragmentCapableXmlDictionaryWriter))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.IStreamProvider))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.IXmlBinaryReaderInitializer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.IXmlBinaryWriterInitializer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.IXmlDictionary))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.IXmlTextReaderInitializer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.IXmlTextWriterInitializer))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.OnXmlDictionaryReaderClose))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.UniqueId))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.XmlBinaryReaderSession))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.XmlBinaryWriterSession))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.XmlDictionary))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.XmlDictionaryReader))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.XmlDictionaryReaderQuotas))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.XmlDictionaryReaderQuotaTypes))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.XmlDictionaryString))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Xml.XmlDictionaryWriter))]
