trigger: none

schedules:
- cron: "0 13 * * *" # 1PM UTC => 5 AM PST
  displayName: HttpStress nightly run
  branches:
    include:
    - master

pool:
  name: Hosted VS2017

variables:
  - template: ../variables.yml
  - name: httpStressProject
    value: $(sourcesRoot)/System.Net.Http/tests/StressTests/HttpStress/

steps:
- checkout: self
  clean: true
  fetchDepth: 0
  lfs: false

- powershell: |
    .\$(buildScriptFileName).cmd -ci -c $(BUILD_CONFIGURATION)
  displayName: Build Corefx

- powershell: |
    cd '$(HttpStressProject)'
    # Load testhost sdk in environment
    . .\load-corefx-testhost.ps1 -c $(BUILD_CONFIGURATION) -b
    # Run the stress suite
    dotnet run -c $(BUILD_CONFIGURATION) -- $(HTTPSTRESS_ARGS)
  displayName: Run HttpStress

- task: PublishBuildArtifacts@1
  displayName: Publish Logs
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(BUILD_CONFIGURATION)'
    PublishLocation: Container
    ArtifactName: 'httpstress_$(Agent.Os)_$(Agent.JobName)'
  continueOnError: true
  condition: always()
