trigger: none

schedules:
- cron: "0 13 * * *" # 1PM UTC => 5 AM PST
  displayName: HttpStress nightly run
  branches:
    include:
    - master

pool:
  name: Hosted Ubuntu 1604

variables:
  - template: ../variables.yml
  - name: httpStressProject
    value: $(sourcesRoot)/System.Net.Http/tests/StressTests/HttpStress/
  - name: sdkBaseImage
    value: sdk-corefx-current
  - name: httpStressImage
    value: httpstress

steps:
- checkout: self
  clean: true
  fetchDepth: 0
  lfs: false

- bash: |
    docker build -t $(sdkBaseImage) --build-arg CONFIGURATION=$(BUILD_CONFIGURATION) --build-arg BUILD_SCRIPT_NAME=$(buildScriptFileName) -f $(HttpStressProject)corefx.Dockerfile .
  displayName: Build Corefx

- bash: |
    cd '$(HttpStressProject)'
    docker build -t $(httpStressImage) --build-arg SDK_BASE_IMAGE=$(sdkBaseImage) --build-arg CONFIGURATION=$(BUILD_CONFIGURATION) .
  displayName: Build HttpStress

- bash: |
    cd '$(HttpStressProject)'
    docker-compose up --abort-on-container-exit --no-color
  displayName: Run HttpStress
  env:
    HTTPSTRESS_IMAGE: $(httpStressImage)
