//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Text.Encoding.CodePages.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory to continue the execution of the program..
        /// </summary>
        internal static string Arg_OutOfMemoryException {
            get {
                return ResourceManager.GetString("Arg_OutOfMemoryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a supported code page..
        /// </summary>
        internal static string Argument_CodepageNotSupported {
            get {
                return ResourceManager.GetString("Argument_CodepageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncoderFallbackNotEmpty {
            get {
                return ResourceManager.GetString("Argument_EncoderFallbackNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output byte buffer is too small to contain the encoded data, encoding &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncodingConversionOverflowBytes {
            get {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output char buffer is too small to contain the decoded characters, encoding &apos;{0}&apos; fallback &apos;{1}&apos;..
        /// </summary>
        internal static string Argument_EncodingConversionOverflowChars {
            get {
                return ResourceManager.GetString("Argument_EncodingConversionOverflowChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String contains invalid Unicode code points..
        /// </summary>
        internal static string Argument_InvalidCharSequenceNoIndex {
            get {
                return ResourceManager.GetString("Argument_InvalidCharSequenceNoIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive fallback not allowed for character \u{0:X4}..
        /// </summary>
        internal static string Argument_RecursiveFallback {
            get {
                return ResourceManager.GetString("Argument_RecursiveFallback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursive fallback not allowed for bytes {0}..
        /// </summary>
        internal static string Argument_RecursiveFallbackBytes {
            get {
                return ResourceManager.GetString("Argument_RecursiveFallbackBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array cannot be null..
        /// </summary>
        internal static string ArgumentNull_Array {
            get {
                return ResourceManager.GetString("ArgumentNull_Array", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many characters. The resulting number of bytes is larger than what can be returned as an int..
        /// </summary>
        internal static string ArgumentOutOfRange_GetByteCountOverflow {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GetByteCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many bytes. The resulting number of chars is larger than what can be returned as an int..
        /// </summary>
        internal static string ArgumentOutOfRange_GetCharCountOverflow {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_GetCharCountOverflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was out of range. Must be non-negative and less than the size of the collection..
        /// </summary>
        internal static string ArgumentOutOfRange_Index {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index and count must refer to a location within the string..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCount {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index and count must refer to a location within the buffer..
        /// </summary>
        internal static string ArgumentOutOfRange_IndexCountBuffer {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_IndexCountBuffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-negative number required..
        /// </summary>
        internal static string ArgumentOutOfRange_NeedNonNegNum {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_NeedNonNegNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values are between {0} and {1}, inclusive..
        /// </summary>
        internal static string ArgumentOutOfRange_Range {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European (Mac).
        /// </summary>
        internal static string Globalization_cp_10000 {
            get {
                return ResourceManager.GetString("Globalization_cp_10000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (Mac).
        /// </summary>
        internal static string Globalization_cp_10001 {
            get {
                return ResourceManager.GetString("Globalization_cp_10001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (Mac).
        /// </summary>
        internal static string Globalization_cp_10002 {
            get {
                return ResourceManager.GetString("Globalization_cp_10002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (Mac).
        /// </summary>
        internal static string Globalization_cp_10003 {
            get {
                return ResourceManager.GetString("Globalization_cp_10003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (Mac).
        /// </summary>
        internal static string Globalization_cp_10004 {
            get {
                return ResourceManager.GetString("Globalization_cp_10004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (Mac).
        /// </summary>
        internal static string Globalization_cp_10005 {
            get {
                return ResourceManager.GetString("Globalization_cp_10005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (Mac).
        /// </summary>
        internal static string Globalization_cp_10006 {
            get {
                return ResourceManager.GetString("Globalization_cp_10006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (Mac).
        /// </summary>
        internal static string Globalization_cp_10007 {
            get {
                return ResourceManager.GetString("Globalization_cp_10007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (Mac).
        /// </summary>
        internal static string Globalization_cp_10008 {
            get {
                return ResourceManager.GetString("Globalization_cp_10008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian (Mac).
        /// </summary>
        internal static string Globalization_cp_10010 {
            get {
                return ResourceManager.GetString("Globalization_cp_10010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian (Mac).
        /// </summary>
        internal static string Globalization_cp_10017 {
            get {
                return ResourceManager.GetString("Globalization_cp_10017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai (Mac).
        /// </summary>
        internal static string Globalization_cp_10021 {
            get {
                return ResourceManager.GetString("Globalization_cp_10021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European (Mac).
        /// </summary>
        internal static string Globalization_cp_10029 {
            get {
                return ResourceManager.GetString("Globalization_cp_10029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic (Mac).
        /// </summary>
        internal static string Globalization_cp_10079 {
            get {
                return ResourceManager.GetString("Globalization_cp_10079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (Mac).
        /// </summary>
        internal static string Globalization_cp_10081 {
            get {
                return ResourceManager.GetString("Globalization_cp_10081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian (Mac).
        /// </summary>
        internal static string Globalization_cp_10082 {
            get {
                return ResourceManager.GetString("Globalization_cp_10082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Turkish Latin-5).
        /// </summary>
        internal static string Globalization_cp_1026 {
            get {
                return ResourceManager.GetString("Globalization_cp_1026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM Latin-1.
        /// </summary>
        internal static string Globalization_cp_1047 {
            get {
                return ResourceManager.GetString("Globalization_cp_1047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (US-Canada-Euro).
        /// </summary>
        internal static string Globalization_cp_1140 {
            get {
                return ResourceManager.GetString("Globalization_cp_1140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Germany-Euro).
        /// </summary>
        internal static string Globalization_cp_1141 {
            get {
                return ResourceManager.GetString("Globalization_cp_1141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Denmark-Norway-Euro).
        /// </summary>
        internal static string Globalization_cp_1142 {
            get {
                return ResourceManager.GetString("Globalization_cp_1142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Finland-Sweden-Euro).
        /// </summary>
        internal static string Globalization_cp_1143 {
            get {
                return ResourceManager.GetString("Globalization_cp_1143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Italy-Euro).
        /// </summary>
        internal static string Globalization_cp_1144 {
            get {
                return ResourceManager.GetString("Globalization_cp_1144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Spain-Euro).
        /// </summary>
        internal static string Globalization_cp_1145 {
            get {
                return ResourceManager.GetString("Globalization_cp_1145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (UK-Euro).
        /// </summary>
        internal static string Globalization_cp_1146 {
            get {
                return ResourceManager.GetString("Globalization_cp_1146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (France-Euro).
        /// </summary>
        internal static string Globalization_cp_1147 {
            get {
                return ResourceManager.GetString("Globalization_cp_1147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (International-Euro).
        /// </summary>
        internal static string Globalization_cp_1148 {
            get {
                return ResourceManager.GetString("Globalization_cp_1148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Icelandic-Euro).
        /// </summary>
        internal static string Globalization_cp_1149 {
            get {
                return ResourceManager.GetString("Globalization_cp_1149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European (Windows).
        /// </summary>
        internal static string Globalization_cp_1250 {
            get {
                return ResourceManager.GetString("Globalization_cp_1250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (Windows).
        /// </summary>
        internal static string Globalization_cp_1251 {
            get {
                return ResourceManager.GetString("Globalization_cp_1251", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European (Windows).
        /// </summary>
        internal static string Globalization_cp_1252 {
            get {
                return ResourceManager.GetString("Globalization_cp_1252", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (Windows).
        /// </summary>
        internal static string Globalization_cp_1253 {
            get {
                return ResourceManager.GetString("Globalization_cp_1253", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (Windows).
        /// </summary>
        internal static string Globalization_cp_1254 {
            get {
                return ResourceManager.GetString("Globalization_cp_1254", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (Windows).
        /// </summary>
        internal static string Globalization_cp_1255 {
            get {
                return ResourceManager.GetString("Globalization_cp_1255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (Windows).
        /// </summary>
        internal static string Globalization_cp_1256 {
            get {
                return ResourceManager.GetString("Globalization_cp_1256", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltic (Windows).
        /// </summary>
        internal static string Globalization_cp_1257 {
            get {
                return ResourceManager.GetString("Globalization_cp_1257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese (Windows).
        /// </summary>
        internal static string Globalization_cp_1258 {
            get {
                return ResourceManager.GetString("Globalization_cp_1258", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (Johab).
        /// </summary>
        internal static string Globalization_cp_1361 {
            get {
                return ResourceManager.GetString("Globalization_cp_1361", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (CNS).
        /// </summary>
        internal static string Globalization_cp_20000 {
            get {
                return ResourceManager.GetString("Globalization_cp_20000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCA Taiwan.
        /// </summary>
        internal static string Globalization_cp_20001 {
            get {
                return ResourceManager.GetString("Globalization_cp_20001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (Eten).
        /// </summary>
        internal static string Globalization_cp_20002 {
            get {
                return ResourceManager.GetString("Globalization_cp_20002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM5550 Taiwan.
        /// </summary>
        internal static string Globalization_cp_20003 {
            get {
                return ResourceManager.GetString("Globalization_cp_20003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeleText Taiwan.
        /// </summary>
        internal static string Globalization_cp_20004 {
            get {
                return ResourceManager.GetString("Globalization_cp_20004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wang Taiwan.
        /// </summary>
        internal static string Globalization_cp_20005 {
            get {
                return ResourceManager.GetString("Globalization_cp_20005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European (IA5).
        /// </summary>
        internal static string Globalization_cp_20105 {
            get {
                return ResourceManager.GetString("Globalization_cp_20105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German (IA5).
        /// </summary>
        internal static string Globalization_cp_20106 {
            get {
                return ResourceManager.GetString("Globalization_cp_20106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish (IA5).
        /// </summary>
        internal static string Globalization_cp_20107 {
            get {
                return ResourceManager.GetString("Globalization_cp_20107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian (IA5).
        /// </summary>
        internal static string Globalization_cp_20108 {
            get {
                return ResourceManager.GetString("Globalization_cp_20108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.61.
        /// </summary>
        internal static string Globalization_cp_20261 {
            get {
                return ResourceManager.GetString("Globalization_cp_20261", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO-6937.
        /// </summary>
        internal static string Globalization_cp_20269 {
            get {
                return ResourceManager.GetString("Globalization_cp_20269", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Germany).
        /// </summary>
        internal static string Globalization_cp_20273 {
            get {
                return ResourceManager.GetString("Globalization_cp_20273", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Denmark-Norway).
        /// </summary>
        internal static string Globalization_cp_20277 {
            get {
                return ResourceManager.GetString("Globalization_cp_20277", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Finland-Sweden).
        /// </summary>
        internal static string Globalization_cp_20278 {
            get {
                return ResourceManager.GetString("Globalization_cp_20278", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Italy).
        /// </summary>
        internal static string Globalization_cp_20280 {
            get {
                return ResourceManager.GetString("Globalization_cp_20280", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Spain).
        /// </summary>
        internal static string Globalization_cp_20284 {
            get {
                return ResourceManager.GetString("Globalization_cp_20284", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (UK).
        /// </summary>
        internal static string Globalization_cp_20285 {
            get {
                return ResourceManager.GetString("Globalization_cp_20285", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Japanese katakana).
        /// </summary>
        internal static string Globalization_cp_20290 {
            get {
                return ResourceManager.GetString("Globalization_cp_20290", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (France).
        /// </summary>
        internal static string Globalization_cp_20297 {
            get {
                return ResourceManager.GetString("Globalization_cp_20297", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Arabic).
        /// </summary>
        internal static string Globalization_cp_20420 {
            get {
                return ResourceManager.GetString("Globalization_cp_20420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Greek).
        /// </summary>
        internal static string Globalization_cp_20423 {
            get {
                return ResourceManager.GetString("Globalization_cp_20423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Hebrew).
        /// </summary>
        internal static string Globalization_cp_20424 {
            get {
                return ResourceManager.GetString("Globalization_cp_20424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Korean Extended).
        /// </summary>
        internal static string Globalization_cp_20833 {
            get {
                return ResourceManager.GetString("Globalization_cp_20833", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Thai).
        /// </summary>
        internal static string Globalization_cp_20838 {
            get {
                return ResourceManager.GetString("Globalization_cp_20838", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (KOI8-R).
        /// </summary>
        internal static string Globalization_cp_20866 {
            get {
                return ResourceManager.GetString("Globalization_cp_20866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Icelandic).
        /// </summary>
        internal static string Globalization_cp_20871 {
            get {
                return ResourceManager.GetString("Globalization_cp_20871", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Cyrillic Russian).
        /// </summary>
        internal static string Globalization_cp_20880 {
            get {
                return ResourceManager.GetString("Globalization_cp_20880", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Turkish).
        /// </summary>
        internal static string Globalization_cp_20905 {
            get {
                return ResourceManager.GetString("Globalization_cp_20905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM Latin-1.
        /// </summary>
        internal static string Globalization_cp_20924 {
            get {
                return ResourceManager.GetString("Globalization_cp_20924", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JIS 0208-1990 and 0212-1990).
        /// </summary>
        internal static string Globalization_cp_20932 {
            get {
                return ResourceManager.GetString("Globalization_cp_20932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (GB2312-80).
        /// </summary>
        internal static string Globalization_cp_20936 {
            get {
                return ResourceManager.GetString("Globalization_cp_20936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean Wansung.
        /// </summary>
        internal static string Globalization_cp_20949 {
            get {
                return ResourceManager.GetString("Globalization_cp_20949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Cyrillic Serbian-Bulgarian).
        /// </summary>
        internal static string Globalization_cp_21025 {
            get {
                return ResourceManager.GetString("Globalization_cp_21025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ext Alpha Lowercase.
        /// </summary>
        internal static string Globalization_cp_21027 {
            get {
                return ResourceManager.GetString("Globalization_cp_21027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (KOI8-U).
        /// </summary>
        internal static string Globalization_cp_21866 {
            get {
                return ResourceManager.GetString("Globalization_cp_21866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European (ISO).
        /// </summary>
        internal static string Globalization_cp_28592 {
            get {
                return ResourceManager.GetString("Globalization_cp_28592", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin 3 (ISO).
        /// </summary>
        internal static string Globalization_cp_28593 {
            get {
                return ResourceManager.GetString("Globalization_cp_28593", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltic (ISO).
        /// </summary>
        internal static string Globalization_cp_28594 {
            get {
                return ResourceManager.GetString("Globalization_cp_28594", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (ISO).
        /// </summary>
        internal static string Globalization_cp_28595 {
            get {
                return ResourceManager.GetString("Globalization_cp_28595", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (ISO).
        /// </summary>
        internal static string Globalization_cp_28596 {
            get {
                return ResourceManager.GetString("Globalization_cp_28596", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (ISO).
        /// </summary>
        internal static string Globalization_cp_28597 {
            get {
                return ResourceManager.GetString("Globalization_cp_28597", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (ISO-Visual).
        /// </summary>
        internal static string Globalization_cp_28598 {
            get {
                return ResourceManager.GetString("Globalization_cp_28598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (ISO).
        /// </summary>
        internal static string Globalization_cp_28599 {
            get {
                return ResourceManager.GetString("Globalization_cp_28599", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estonian (ISO).
        /// </summary>
        internal static string Globalization_cp_28603 {
            get {
                return ResourceManager.GetString("Globalization_cp_28603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latin 9 (ISO).
        /// </summary>
        internal static string Globalization_cp_28605 {
            get {
                return ResourceManager.GetString("Globalization_cp_28605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europa.
        /// </summary>
        internal static string Globalization_cp_29001 {
            get {
                return ResourceManager.GetString("Globalization_cp_29001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (US-Canada).
        /// </summary>
        internal static string Globalization_cp_37 {
            get {
                return ResourceManager.GetString("Globalization_cp_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (ISO-Logical).
        /// </summary>
        internal static string Globalization_cp_38598 {
            get {
                return ResourceManager.GetString("Globalization_cp_38598", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM United States.
        /// </summary>
        internal static string Globalization_cp_437 {
            get {
                return ResourceManager.GetString("Globalization_cp_437", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (International).
        /// </summary>
        internal static string Globalization_cp_500 {
            get {
                return ResourceManager.GetString("Globalization_cp_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Defined.
        /// </summary>
        internal static string Globalization_cp_50000 {
            get {
                return ResourceManager.GetString("Globalization_cp_50000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JIS).
        /// </summary>
        internal static string Globalization_cp_50220 {
            get {
                return ResourceManager.GetString("Globalization_cp_50220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JIS-Allow 1 byte Kana).
        /// </summary>
        internal static string Globalization_cp_50221 {
            get {
                return ResourceManager.GetString("Globalization_cp_50221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (JIS-Allow 1 byte Kana - SO/SI).
        /// </summary>
        internal static string Globalization_cp_50222 {
            get {
                return ResourceManager.GetString("Globalization_cp_50222", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (ISO).
        /// </summary>
        internal static string Globalization_cp_50225 {
            get {
                return ResourceManager.GetString("Globalization_cp_50225", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (ISO-2022).
        /// </summary>
        internal static string Globalization_cp_50227 {
            get {
                return ResourceManager.GetString("Globalization_cp_50227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (ISO-2022).
        /// </summary>
        internal static string Globalization_cp_50229 {
            get {
                return ResourceManager.GetString("Globalization_cp_50229", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Japanese and Japanese Katakana).
        /// </summary>
        internal static string Globalization_cp_50930 {
            get {
                return ResourceManager.GetString("Globalization_cp_50930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Japanese and US-Canada).
        /// </summary>
        internal static string Globalization_cp_50931 {
            get {
                return ResourceManager.GetString("Globalization_cp_50931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Korean and Korean Extended).
        /// </summary>
        internal static string Globalization_cp_50933 {
            get {
                return ResourceManager.GetString("Globalization_cp_50933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Simplified Chinese).
        /// </summary>
        internal static string Globalization_cp_50935 {
            get {
                return ResourceManager.GetString("Globalization_cp_50935", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Traditional Chinese).
        /// </summary>
        internal static string Globalization_cp_50937 {
            get {
                return ResourceManager.GetString("Globalization_cp_50937", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Japanese and Japanese-Latin).
        /// </summary>
        internal static string Globalization_cp_50939 {
            get {
                return ResourceManager.GetString("Globalization_cp_50939", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (EUC).
        /// </summary>
        internal static string Globalization_cp_51932 {
            get {
                return ResourceManager.GetString("Globalization_cp_51932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (EUC).
        /// </summary>
        internal static string Globalization_cp_51936 {
            get {
                return ResourceManager.GetString("Globalization_cp_51936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean (EUC).
        /// </summary>
        internal static string Globalization_cp_51949 {
            get {
                return ResourceManager.GetString("Globalization_cp_51949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (HZ).
        /// </summary>
        internal static string Globalization_cp_52936 {
            get {
                return ResourceManager.GetString("Globalization_cp_52936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (GB18030).
        /// </summary>
        internal static string Globalization_cp_54936 {
            get {
                return ResourceManager.GetString("Globalization_cp_54936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Devanagari.
        /// </summary>
        internal static string Globalization_cp_57002 {
            get {
                return ResourceManager.GetString("Globalization_cp_57002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Bengali.
        /// </summary>
        internal static string Globalization_cp_57003 {
            get {
                return ResourceManager.GetString("Globalization_cp_57003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Tamil.
        /// </summary>
        internal static string Globalization_cp_57004 {
            get {
                return ResourceManager.GetString("Globalization_cp_57004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Telugu.
        /// </summary>
        internal static string Globalization_cp_57005 {
            get {
                return ResourceManager.GetString("Globalization_cp_57005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Assamese.
        /// </summary>
        internal static string Globalization_cp_57006 {
            get {
                return ResourceManager.GetString("Globalization_cp_57006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Oriya.
        /// </summary>
        internal static string Globalization_cp_57007 {
            get {
                return ResourceManager.GetString("Globalization_cp_57007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Kannada.
        /// </summary>
        internal static string Globalization_cp_57008 {
            get {
                return ResourceManager.GetString("Globalization_cp_57008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Malayalam.
        /// </summary>
        internal static string Globalization_cp_57009 {
            get {
                return ResourceManager.GetString("Globalization_cp_57009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Gujarati.
        /// </summary>
        internal static string Globalization_cp_57010 {
            get {
                return ResourceManager.GetString("Globalization_cp_57010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISCII Punjabi.
        /// </summary>
        internal static string Globalization_cp_57011 {
            get {
                return ResourceManager.GetString("Globalization_cp_57011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (ASMO 708).
        /// </summary>
        internal static string Globalization_cp_708 {
            get {
                return ResourceManager.GetString("Globalization_cp_708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (DOS).
        /// </summary>
        internal static string Globalization_cp_720 {
            get {
                return ResourceManager.GetString("Globalization_cp_720", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek (DOS).
        /// </summary>
        internal static string Globalization_cp_737 {
            get {
                return ResourceManager.GetString("Globalization_cp_737", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baltic (DOS).
        /// </summary>
        internal static string Globalization_cp_775 {
            get {
                return ResourceManager.GetString("Globalization_cp_775", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Western European (DOS).
        /// </summary>
        internal static string Globalization_cp_850 {
            get {
                return ResourceManager.GetString("Globalization_cp_850", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Central European (DOS).
        /// </summary>
        internal static string Globalization_cp_852 {
            get {
                return ResourceManager.GetString("Globalization_cp_852", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM Cyrillic.
        /// </summary>
        internal static string Globalization_cp_855 {
            get {
                return ResourceManager.GetString("Globalization_cp_855", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish (DOS).
        /// </summary>
        internal static string Globalization_cp_857 {
            get {
                return ResourceManager.GetString("Globalization_cp_857", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM Multilingual Latin I.
        /// </summary>
        internal static string Globalization_cp_858 {
            get {
                return ResourceManager.GetString("Globalization_cp_858", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (DOS).
        /// </summary>
        internal static string Globalization_cp_860 {
            get {
                return ResourceManager.GetString("Globalization_cp_860", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic (DOS).
        /// </summary>
        internal static string Globalization_cp_861 {
            get {
                return ResourceManager.GetString("Globalization_cp_861", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hebrew (DOS).
        /// </summary>
        internal static string Globalization_cp_862 {
            get {
                return ResourceManager.GetString("Globalization_cp_862", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Canadian (DOS).
        /// </summary>
        internal static string Globalization_cp_863 {
            get {
                return ResourceManager.GetString("Globalization_cp_863", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic (864).
        /// </summary>
        internal static string Globalization_cp_864 {
            get {
                return ResourceManager.GetString("Globalization_cp_864", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordic (DOS).
        /// </summary>
        internal static string Globalization_cp_865 {
            get {
                return ResourceManager.GetString("Globalization_cp_865", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyrillic (DOS).
        /// </summary>
        internal static string Globalization_cp_866 {
            get {
                return ResourceManager.GetString("Globalization_cp_866", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek, Modern (DOS).
        /// </summary>
        internal static string Globalization_cp_869 {
            get {
                return ResourceManager.GetString("Globalization_cp_869", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Multilingual Latin-2).
        /// </summary>
        internal static string Globalization_cp_870 {
            get {
                return ResourceManager.GetString("Globalization_cp_870", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thai (Windows).
        /// </summary>
        internal static string Globalization_cp_874 {
            get {
                return ResourceManager.GetString("Globalization_cp_874", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBM EBCDIC (Greek Modern).
        /// </summary>
        internal static string Globalization_cp_875 {
            get {
                return ResourceManager.GetString("Globalization_cp_875", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese (Shift-JIS).
        /// </summary>
        internal static string Globalization_cp_932 {
            get {
                return ResourceManager.GetString("Globalization_cp_932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Simplified (GB2312).
        /// </summary>
        internal static string Globalization_cp_936 {
            get {
                return ResourceManager.GetString("Globalization_cp_936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string Globalization_cp_949 {
            get {
                return ResourceManager.GetString("Globalization_cp_949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese Traditional (Big5).
        /// </summary>
        internal static string Globalization_cp_950 {
            get {
                return ResourceManager.GetString("Globalization_cp_950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a resource entry for the encoding codepage &apos;{0} - {1}&apos;.
        /// </summary>
        internal static string MissingEncodingNameResource {
            get {
                return ResourceManager.GetString("MissingEncodingNameResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data is available for encoding {0}..
        /// </summary>
        internal static string NotSupported_NoCodepageData {
            get {
                return ResourceManager.GetString("NotSupported_NoCodepageData", resourceCulture);
            }
        }
    }
}
