// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.IOControlCode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.IPPacketInformation))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.IPProtectionLevel))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.IPv6MulticastOption))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.LingerOption))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.MulticastOption))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.NetworkStream))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.ProtocolFamily))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.ProtocolType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SelectMode))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SendPacketsElement))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.Socket))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketAsyncEventArgs))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketAsyncOperation))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketFlags))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketInformation))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketInformationOptions))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketOptionLevel))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketOptionName))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketShutdown))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.SocketType))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.TcpClient))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.TcpListener))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.TransmitFileOptions))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.UdpClient))]
[assembly: System.Runtime.CompilerServices.TypeForwardedTo(typeof(System.Net.Sockets.UdpReceiveResult))]
