// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Reflection;
using Xunit;
using Xunit.Sdk;

namespace System.Text.RegularExpressions.Tests
{
    public class RegexParserTests
    {
        private static readonly Type s_parseExceptionType;
        private static readonly FieldInfo s_parseErrorField;

        static RegexParserTests()
        {
            // On Full Framework RegexParseException doesn't exist and on uapaot reflection is blocked.
            if (!PlatformDetection.IsNetNative && !PlatformDetection.IsFullFramework)
            {
                s_parseExceptionType = typeof(Regex).Assembly.GetType("System.Text.RegularExpressions.RegexParseException", true);
                s_parseErrorField = s_parseExceptionType.GetField("_error", BindingFlags.NonPublic | BindingFlags.Instance);
            }
        }

        [Theory]
        // Basic
        [InlineData("", RegexOptions.None, null, true)]
        [InlineData(" ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("  ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?#)", RegexOptions.None, null, true)]
        [InlineData("(?# )", RegexOptions.None, null, true)]
        [InlineData("(?#", RegexOptions.None, RegexParseError.UnterminatedComment, true)]
        [InlineData("(?# ", RegexOptions.None, RegexParseError.UnterminatedComment, true)]
        [InlineData("(?#)(?#)", RegexOptions.None, null, true)]
        [InlineData("(?#)(?#)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?#) (?#)", RegexOptions.None, null, true)]
        [InlineData("(?#) (?#)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(@"[a\p{Lu}(?#)b]", RegexOptions.None, null, true)]
        [InlineData(@"[a\0(?#)b]", RegexOptions.None, null, true)]
        [InlineData(@"[a\a(?#)b]", RegexOptions.None, null, true)]
        [InlineData(@"[a\x00(?#)b]", RegexOptions.None, null, true)]
        [InlineData(@"[a\u0000(?#)b]", RegexOptions.None, null, true)]
        [InlineData(@"[a\](?#)b]", RegexOptions.None, null, true)]
        [InlineData("(?", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(? ", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(? ", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?i)", RegexOptions.None, null, true)]
        [InlineData("(?im)", RegexOptions.None, null, true)]
        [InlineData("(?im-x)", RegexOptions.None, null, true)]
        [InlineData("(?im-x+n)", RegexOptions.None, null, true)]
        [InlineData("(?i) ", RegexOptions.None, null, true)]
        [InlineData("(?x) ", RegexOptions.None, null, true)]
        [InlineData(" (?x) ", RegexOptions.None, null, true)]
        [InlineData(" (?-x) ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(" ( (?-x) ) ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(" (?-x:) ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(" (?-x: ) ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(" (?-x: (?+x: ) ) ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?-x", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?-x ", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?-x :", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?-x )", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?-x :)", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(")", RegexOptions.None, RegexParseError.TooManyParentheses, true)]
        [InlineData("a", RegexOptions.None, null, true)]
        [InlineData("ab", RegexOptions.None, null, true)]
        [InlineData("a*", RegexOptions.None, null, true)]
        [InlineData("a*?", RegexOptions.None, null, true)]
        [InlineData("a+", RegexOptions.None, null, true)]
        [InlineData("a+?", RegexOptions.None, null, true)]
        [InlineData("a?", RegexOptions.None, null, true)]
        [InlineData("a??", RegexOptions.None, null, true)]
        [InlineData("()", RegexOptions.None, null, true)]
        [InlineData("(a)", RegexOptions.None, null, true)]
        [InlineData("(", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(a", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("|", RegexOptions.None, null, true)]
        [InlineData(" |", RegexOptions.None, null, true)]
        [InlineData("| ", RegexOptions.None, null, true)]
        [InlineData(" | ", RegexOptions.None, null, true)]
        [InlineData("|", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(" |", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("| ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(" | ", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("||", RegexOptions.None, null, true)]
        [InlineData("(|)", RegexOptions.None, null, true)]
        [InlineData("a{0}", RegexOptions.None, null, true)]
        [InlineData("a{0,}", RegexOptions.None, null, true)]
        [InlineData("a{0,1}", RegexOptions.None, null, true)]
        [InlineData("a{1,0}", RegexOptions.None, RegexParseError.IllegalRange, true)]
        [InlineData("a{0}?", RegexOptions.None, null, true)]
        [InlineData("a{0,}?", RegexOptions.None, null, true)]
        [InlineData("a{0,1}?", RegexOptions.None, null, true)]
        [InlineData("a{", RegexOptions.None, null, true)]
        [InlineData("a{0", RegexOptions.None, null, true)]
        [InlineData("a{0,", RegexOptions.None, null, true)]
        [InlineData("a{0,1", RegexOptions.None, null, true)]
        [InlineData("a{0 }", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("a{0, }", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("a{0 ,}", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("a{0 ,1}", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("a{0, 1}", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("a{0,1 }", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("a* ?", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("a* ?", RegexOptions.None, null, true)]
        [InlineData("*", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData("(*)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData("a**", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData("+", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData("(+)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData("a*+", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData("?", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData("(?)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData("a*??", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData("{0}", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData("({0})", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData("a*{0}", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData("{0", RegexOptions.None, null, true)]
        [InlineData("({0)", RegexOptions.None, null, true)]
        [InlineData("a*{0", RegexOptions.None, null, true)]
        [InlineData(@"\w", RegexOptions.None, null, true)]
        [InlineData(@"\b\B\A\G\Z\z\w\W\s\W\s\S\d\D", RegexOptions.None, null, true)]
        [InlineData(@"\c", RegexOptions.None, RegexParseError.MissingControl, true)]
        [InlineData(@"\c<", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"\ca", RegexOptions.None, null, true)]
        [InlineData(@"\cA", RegexOptions.None, null, true)]
        [InlineData(@"\c A", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"\c(a)", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"\c>", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"\c?", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"\c@", RegexOptions.None, null, true)]
        [InlineData(@"\c^", RegexOptions.None, null, true)]
        [InlineData(@"\c_", RegexOptions.None, null, true)]
        [InlineData(@"\c`", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"\c{", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"\cz", RegexOptions.None, null, true)]
        [InlineData(@"\cZ", RegexOptions.None, null, true)]
        [InlineData(@"\m", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\x", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\x ", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\x0", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\x0 ", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\x00", RegexOptions.None, null, true)]
        [InlineData(@"\x00 ", RegexOptions.None, null, true)]
        [InlineData(@"\x000", RegexOptions.None, null, true)]
        [InlineData(@"\xff", RegexOptions.None, null, true)]
        [InlineData(@"\xFF", RegexOptions.None, null, true)]
        [InlineData(@"\xfF", RegexOptions.None, null, true)]
        [InlineData(@"\xfff", RegexOptions.None, null, true)]
        [InlineData(@"\xgg", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\m ", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\u", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\u0", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\u00", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\u000", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\u0000", RegexOptions.None, null, true)]
        [InlineData(@"\u0000 ", RegexOptions.None, null, true)]
        [InlineData(@"\u ", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\u0 ", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\ugggg", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"\0", RegexOptions.None, null, true)]
        [InlineData(@"\0 ", RegexOptions.None, null, true)]
        [InlineData(@"\00", RegexOptions.None, null, true)]
        [InlineData(@"\00 ", RegexOptions.None, null, true)]
        [InlineData(@"\000", RegexOptions.None, null, true)]
        [InlineData(@"\000 ", RegexOptions.None, null, true)]
        [InlineData(@"\0000", RegexOptions.None, null, true)]
        [InlineData(@"\0000 ", RegexOptions.None, null, true)]
        [InlineData(@"\7", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"\78", RegexOptions.None, null, true)]
        [InlineData(@"\8", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"\40", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\401", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\37", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\371", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\0000", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\k", RegexOptions.None, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"\k ", RegexOptions.None, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"\k<", RegexOptions.None, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"\k< ", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\k<0", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\k<0 ", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\k<0>", RegexOptions.None, null, true)]
        [InlineData(@"\k<0> ", RegexOptions.None, null, true)]
        [InlineData(@"\k<00> ", RegexOptions.None, null, true)]
        [InlineData(@"\k<a> ", RegexOptions.None, RegexParseError.UndefinedNameRef, true)]
        [InlineData(@"(?<a>)\k<a> ", RegexOptions.None, null, true)]
        [InlineData(@"\k", RegexOptions.ECMAScript, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"\k ", RegexOptions.ECMAScript, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"\k<", RegexOptions.ECMAScript, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"\k< ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\k<0", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\k<0 ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\k<0>", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\k<0> ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\k'", RegexOptions.None, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"\k' ", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\k'0", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\k'0 ", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\k'0'", RegexOptions.None, null, true)]
        [InlineData(@"\k'0' ", RegexOptions.None, null, true)]
        [InlineData(@"\k'00' ", RegexOptions.None, null, true)]
        [InlineData(@"\k'a' ", RegexOptions.None, RegexParseError.UndefinedNameRef, true)]
        [InlineData(@"(?<a>)\k'a' ", RegexOptions.None, null, true)]
        [InlineData(@"\k<0' ", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\k'0> ", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\", RegexOptions.None, RegexParseError.IllegalEndEscape, true)]
        [InlineData(@"\ ", RegexOptions.None, null, true)]
        [InlineData(@"\<", RegexOptions.None, null, true)]
        [InlineData(@"\< ", RegexOptions.None, null, true)]
        [InlineData(@"\<0", RegexOptions.None, null, true)]
        [InlineData(@"\<0 ", RegexOptions.None, null, true)]
        [InlineData(@"\<0>", RegexOptions.None, null, true)]
        [InlineData(@"\<0> ", RegexOptions.None, null, true)]
        [InlineData(@"\<00> ", RegexOptions.None, null, true)]
        [InlineData(@"\<a> ", RegexOptions.None, RegexParseError.UndefinedNameRef, true)]
        [InlineData(@"(?<a>)\<a> ", RegexOptions.None, null, true)]
        [InlineData(@"\", RegexOptions.ECMAScript, RegexParseError.IllegalEndEscape, true)]
        [InlineData(@"\ ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\<", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\< ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\<0", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\<0 ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\<0>", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\<0> ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\'", RegexOptions.None, null, true)]
        [InlineData(@"\' ", RegexOptions.None, null, true)]
        [InlineData(@"\'0", RegexOptions.None, null, true)]
        [InlineData(@"\'0 ", RegexOptions.None, null, true)]
        [InlineData(@"\'0'", RegexOptions.None, null, true)]
        [InlineData(@"\'0' ", RegexOptions.None, null, true)]
        [InlineData(@"\'00' ", RegexOptions.None, null, true)]
        [InlineData(@"\'a' ", RegexOptions.None, RegexParseError.UndefinedNameRef, true)]
        [InlineData(@"(?<a>)\'a' ", RegexOptions.None, null, true)]
        [InlineData(@"\<0' ", RegexOptions.None, null, true)]
        [InlineData(@"\'0> ", RegexOptions.None, null, true)]
        [InlineData("\\p{Cc}", RegexOptions.None, null, true)]
        [InlineData("\\p{ Cc }", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData("\\p{ Cc }", RegexOptions.IgnorePatternWhitespace, RegexParseError.IncompleteSlashP, true)]
        [InlineData("\\p {Cc}", RegexOptions.IgnorePatternWhitespace, RegexParseError.MalformedSlashP, true)]
        [InlineData("\\p{xxx}", RegexOptions.None, RegexParseError.UnknownUnicodeProperty, true)]
        [InlineData("\\p", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData("\\p{", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData("\\p{}", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData("\\p{} ", RegexOptions.None, RegexParseError.UnknownUnicodeProperty, true)]
        [InlineData("\\p {} ", RegexOptions.None, RegexParseError.MalformedSlashP, true)]
        [InlineData("\\p{Cc ", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData("\\p{IsArabicPresentationForms-A}", RegexOptions.None, null, true)]
        [InlineData("(?:)", RegexOptions.None, null, true)]
        [InlineData("(?:a)", RegexOptions.None, null, true)]
        [InlineData("(?:", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?: ", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?=)", RegexOptions.None, null, true)]
        [InlineData("(?=a)", RegexOptions.None, null, true)]
        [InlineData("(?=", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?= ", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?!)", RegexOptions.None, null, true)]
        [InlineData("(?!a)", RegexOptions.None, null, true)]
        [InlineData("(?!", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?! ", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?>)", RegexOptions.None, null, true)]
        [InlineData("(?>a)", RegexOptions.None, null, true)]
        [InlineData("(?>", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?> ", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?<=)", RegexOptions.None, null, true)]
        [InlineData("(?<=a)", RegexOptions.None, null, true)]
        [InlineData("(?<=", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?<= ", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?<!)", RegexOptions.None, null, true)]
        [InlineData("(?<!a)", RegexOptions.None, null, true)]
        [InlineData("(?<!", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?<! ", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?<", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?<>", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<a", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?<a>", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?<a>a", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?<a>a)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a >a)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<a >a)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?< a>a)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?< a>a)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?< a >a)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?< a >a)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<ab>a)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<0>a)", RegexOptions.IgnorePatternWhitespace, RegexParseError.CapnumNotZero, true)]
        [InlineData("(?<1>a)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<10>a)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<1>)", RegexOptions.None, null, true)]
        [InlineData("(?<1> )", RegexOptions.None, null, true)]
        [InlineData("(?<1> )", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?'a')", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?(", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?(0", RegexOptions.IgnorePatternWhitespace, RegexParseError.MalformedReference, true)]
        [InlineData("(?(0)", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?(0))", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?(0)a)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?(0)a|)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?(0)a|b)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?(0)a|b|)", RegexOptions.IgnorePatternWhitespace, RegexParseError.TooManyAlternates, true)]
        [InlineData("(?(0)a|b|c)", RegexOptions.IgnorePatternWhitespace, RegexParseError.TooManyAlternates, true)]
        [InlineData("(?(0 )", RegexOptions.IgnorePatternWhitespace, RegexParseError.MalformedReference, true)]
        [InlineData("(?(1))", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedReference, true)]
        [InlineData("(?(00))", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?(a))", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a>)(?(a))", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a>)(?(a ))", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a>)(?( a))", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?(()a()))", RegexOptions.None, null, true)]
        [InlineData("(?((?<x>)a(?<y>)))", RegexOptions.None, null, true)]
        [InlineData("(?(?'", RegexOptions.IgnorePatternWhitespace, RegexParseError.AlternationCantCapture, true)]
        [InlineData("(?(?'x'))", RegexOptions.IgnorePatternWhitespace, RegexParseError.AlternationCantCapture, true)]
        [InlineData("(?(?#", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnterminatedComment, true)]
        [InlineData("(?(?#)", RegexOptions.IgnorePatternWhitespace, RegexParseError.AlternationCantHaveComment, true)]
        [InlineData("(?(?#))", RegexOptions.IgnorePatternWhitespace, RegexParseError.AlternationCantHaveComment, true)]
        [InlineData("(?(?<", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?(?<a", RegexOptions.IgnorePatternWhitespace, RegexParseError.AlternationCantCapture, true)]
        [InlineData("(?(?<a>", RegexOptions.IgnorePatternWhitespace, RegexParseError.AlternationCantCapture, true)]
        [InlineData("(?(?<a>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.AlternationCantCapture, true)]
        [InlineData("(?(?<a>))", RegexOptions.IgnorePatternWhitespace, RegexParseError.AlternationCantCapture, true)]
        [InlineData("(?(?<=))", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?(?<!))", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(@"\1", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"\1 ", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()\1", RegexOptions.None, null, true)]
        [InlineData(@"()\1 ", RegexOptions.None, null, true)]
        [InlineData(@"()\10 ", RegexOptions.None, null, true)]
        [InlineData(@"\1", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\1 ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"()\1", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"()\1 ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"()\10 ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"()()()()()()()()()()\10 ", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"[", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[ ", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[]", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[] ", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[a]", RegexOptions.None, null, true)]
        [InlineData(@"[a] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[a- ", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[a-]", RegexOptions.None, null, true)]
        [InlineData(@"[a-] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-b]", RegexOptions.None, null, true)]
        [InlineData(@"[a-b] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-[b]] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-b-[c]] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-[b]-c] ", RegexOptions.None, RegexParseError.SubtractionMustBeLast, true)]
        [InlineData(@"[[a]-b] ", RegexOptions.None, null, true)]
        [InlineData(@"[[a]-[b]] ", RegexOptions.None, null, true)]
        [InlineData(@"[\w-a] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-\w] ", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"[\p{llll}-a] ", RegexOptions.None, RegexParseError.UnknownUnicodeProperty, true)]
        [InlineData(@"[\p{Lu}-a] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-\p{Lu}] ", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"[a-[:Ll:]] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-[:Ll]] ", RegexOptions.None, null, true)]
        [InlineData(@"[a-[:", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[a-[:L", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[a-[:L:", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[a-[:L:]", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[\-]", RegexOptions.None, null, true)]
        [InlineData(@"[a-b-c] ", RegexOptions.None, null, true)]
        [InlineData(@"[-b-c] ", RegexOptions.None, null, true)]
        [InlineData(@"[-[b] ", RegexOptions.None, null, true)]
        [InlineData(@"[-[b]] ", RegexOptions.None, null, true)]
        [InlineData(@"[--b ", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[--b] ", RegexOptions.None, null, true)]
        [InlineData(@"[--[b ", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[--[b] ", RegexOptions.None, RegexParseError.SubtractionMustBeLast, true)]
        [InlineData(@"[--[b]] ", RegexOptions.None, null, true)]
        [InlineData(@"[a--[b ", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[,--[a] ", RegexOptions.None, null, true)]
        [InlineData(@"[,--[a]] ", RegexOptions.None, null, true)]
        [InlineData(@"[\s-a]", RegexOptions.None, null, true)]
        [InlineData(@"[\p{Lu}-a]", RegexOptions.None, null, true)]
        [InlineData(@"[\c<-\c>]", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"[\c>-\c<]", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"[\c>-a]", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"[a-\c>]", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"[a--]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[--a]", RegexOptions.None, null, true)]
        [InlineData(@"[a-\-]", RegexOptions.None, null, true)]
        [InlineData(@"[\--a]", RegexOptions.None, null, true)]
        [InlineData(@"[\0-\1]", RegexOptions.None, null, true)]
        [InlineData(@"[\1-\0]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\0-\01]", RegexOptions.None, null, true)]
        [InlineData(@"[\01-\0]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[[:x:]-a]", RegexOptions.None, null, true)]
        [InlineData(@"[a-[:x:]]", RegexOptions.None, null, true)]
        [InlineData(@"[\0-\ca]", RegexOptions.None, null, true)]
        [InlineData(@"[\ca-\0]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\ca-\cA]", RegexOptions.None, null, true)]
        [InlineData(@"[\cA-\ca]", RegexOptions.None, null, true)]
        [InlineData(@"[\u0-\u1]", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"[\u1-\u0]", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"[\u0000-\u0000]", RegexOptions.None, null, true)]
        [InlineData(@"[\u0000-\u0001]", RegexOptions.None, null, true)]
        [InlineData(@"[\u0001-\u0000]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\u0001-a]", RegexOptions.None, null, true)]
        [InlineData(@"[a-\u0001]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[a-a]", RegexOptions.None, null, true)]
        [InlineData(@"[a-A]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[A-a]", RegexOptions.None, null, true)]
        [InlineData(@"[a-a]", RegexOptions.IgnoreCase, null, true)]
        [InlineData(@"[a-A]", RegexOptions.IgnoreCase, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[A-a]", RegexOptions.IgnoreCase, null, true)]
        [InlineData(@"[a-\x61]", RegexOptions.None, null, true)]
        [InlineData(@"[\x61-a]", RegexOptions.None, null, true)]
        [InlineData(@"[a-\x60]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\x62-a]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[a-\x62]", RegexOptions.None, null, true)]
        [InlineData(@"[\3-\cc]", RegexOptions.None, null, true)]
        [InlineData(@"[\cc-\3]", RegexOptions.None, null, true)]
        [InlineData(@"[\2-\cc]", RegexOptions.None, null, true)]
        [InlineData(@"[\cc-\2]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\4-\cc]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\cc-\4]", RegexOptions.None, null, true)]
        [InlineData(@"[\ca-\cb]", RegexOptions.None, null, true)]
        [InlineData(@"[\ca-\cB]", RegexOptions.None, null, true)]
        [InlineData(@"[\cA-\cb]", RegexOptions.None, null, true)]
        [InlineData(@"[\cA-\cB]", RegexOptions.None, null, true)]
        [InlineData(@"[\cb-\ca]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\cb-\cA]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\cB-\ca]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\cB-\cA]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[\--#]", RegexOptions.None, null, true)]
        [InlineData(@"[a-\-b]", RegexOptions.None, null, true)]
        [InlineData(@"[a-\-\-b]", RegexOptions.None, null, true)]
        [InlineData(@"[b-\-a]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[b-\-\-a]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"[a-\-\D]", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"[a-\-\-\D]", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"[a -\-\b]", RegexOptions.None, RegexParseError.ReversedCharRange, true)]
        [InlineData(@"()\2", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()()\2", RegexOptions.None, null, true)]
        [InlineData(@"()\1", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()()\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()()(?n)\1\2", RegexOptions.None, null, true)]
        [InlineData(@"()(?n)()\1\2", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(?n)()()\1\2", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()()(?n)\1\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()(?n)()\1\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(?n)()()\1\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()()(?-n)\1\2", RegexOptions.None, null, true)]
        [InlineData(@"()(?-n)()\1\2", RegexOptions.None, null, true)]
        [InlineData(@"(?-n)()()\1\2", RegexOptions.None, null, true)]
        [InlineData(@"()()(?-n)\1\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()(?-n)()\1\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(?-n)()()\1\2", RegexOptions.ExplicitCapture, null, true)]
        [InlineData(@"()()(?n:\1\2)", RegexOptions.None, null, true)]
        [InlineData(@"()()(?n:\1\2)", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"()()(?-n:\1\2)", RegexOptions.None, null, true)]
        [InlineData(@"()()(?-n:\1\2)", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(?n:)()()\1\2", RegexOptions.None, null, true)]
        [InlineData(@"(?n:)()()\1\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(?-n:)()()\1\2", RegexOptions.None, null, true)]
        [InlineData(@"(?-n:)()()\1\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(?n)(?-n)()()\1\2", RegexOptions.None, null, true)]
        [InlineData(@"(?n)(?-n)()()\1\2", RegexOptions.ExplicitCapture, null, true)]
        [InlineData(@"(?-n)(?n)()()\1\2", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(?-n)(?n)()()\1\2", RegexOptions.ExplicitCapture, RegexParseError.UndefinedBackref, true)]
        // References
        [InlineData(@"[aeiou]", RegexOptions.None, null, true)]
        [InlineData(@"(?<duplicateWord>\w+)\s\k<duplicateWord>\W(?<nextWord>\w+)", RegexOptions.None, null, true)]
        [InlineData(@"((?<One>abc)\d+)?(?<Two>xyz)(.*)", RegexOptions.None, null, true)]
        [InlineData(@"(\w+)\s(\1)", RegexOptions.None, null, true)]
        [InlineData(@"\Bqu\w+", RegexOptions.None, null, true)]
        [InlineData(@"\bare\w*\b", RegexOptions.None, null, true)]
        [InlineData(@"\G(\w+\s?\w*),?", RegexOptions.None, null, true)]
        [InlineData(@"\D+(?<digit>\d+)\D+(?<digit>\d+)?", RegexOptions.None, null, true)]
        [InlineData(@"(\s\d{4}(-(\d{4}&#124;present))?,?)+", RegexOptions.None, null, true)]
        [InlineData(@"^((\w+(\s?)){2,}),\s(\w+\s\w+),(\s\d{4}(-(\d{4}|present))?,?)+", RegexOptions.None, null, true)]
        [InlineData(@"^[0-9-[2468]]+$", RegexOptions.None, null, true)]
        [InlineData(@"[a-z-[0-9]]", RegexOptions.None, null, true)]
        [InlineData(@"[\p{IsBasicLatin}-[\x00-\x7F]]", RegexOptions.None, null, true)]
        [InlineData(@"[\u0000-\uFFFF-[\s\p{P}\p{IsGreek}\x85]]", RegexOptions.None, null, true)]
        [InlineData(@"[a-z-[d-w-[m-o]]]", RegexOptions.None, null, true)]
        [InlineData(@"((\w+(\s?)){2,}", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"[a-z-[djp]]", RegexOptions.None, null, true)]
        [InlineData(@"(\w)\1+.\b", RegexOptions.None, null, true)]
        [InlineData(@"\d{4}\b", RegexOptions.None, null, true)]
        [InlineData(@"\d{1,2},", RegexOptions.None, null, true)]
        [InlineData(@"(?<!(Saturday|Sunday) )\b\w+ \d{1,2}, \d{4}\b", RegexOptions.None, null, true)]
        [InlineData(@"(?<=\b20)\d{2}\b", RegexOptions.None, null, true)]
        [InlineData(@"\b\w+\b(?!\p{P})", RegexOptions.None, null, true)]
        [InlineData(@"\b(?!un)\w+\b", RegexOptions.None, null, true)]
        [InlineData(@"\b(?ix: d \w+)\s", RegexOptions.None, null, true)]
        [InlineData(@"(?:\w+)", RegexOptions.None, null, true)]
        [InlineData(@"(?:\b(?:\w+)\W*)+", RegexOptions.None, null, true)]
        [InlineData(@"(?:\b(?:\w+)\W*)+\.", RegexOptions.None, null, true)]
        [InlineData(@"[^<>]*", RegexOptions.None, null, true)]
        [InlineData(@"\b\w+(?=\sis\b)", RegexOptions.None, null, true)]
        [InlineData(@"[a-z-[m]]", RegexOptions.None, null, true)]
        [InlineData(@"^\D\d{1,5}\D*$", RegexOptions.None, null, true)]
        [InlineData(@"[^0-9]", RegexOptions.None, null, true)]
        [InlineData(@"(\p{IsGreek}+(\s)?)+", RegexOptions.None, null, true)]
        [InlineData(@"\b(\p{IsGreek}+(\s)?)+\p{Pd}\s(\p{IsBasicLatin}+(\s)?)+", RegexOptions.None, null, true)]
        [InlineData(@"\b.*[.?!;:](\s|\z)", RegexOptions.None, null, true)]
        [InlineData(@"^.+", RegexOptions.None, null, true)]
        [InlineData(@"[^o]", RegexOptions.None, null, true)]
        [InlineData(@"\bth[^o]\w+\b", RegexOptions.None, null, true)]
        [InlineData(@"(\P{Sc})+", RegexOptions.None, null, true)]
        [InlineData(@"[^\p{P}\d]", RegexOptions.None, null, true)]
        [InlineData(@"\b[A-Z]\w*\b", RegexOptions.None, null, true)]
        [InlineData(@"\S+?", RegexOptions.None, null, true)]
        [InlineData(@"y\s", RegexOptions.None, null, true)]
        [InlineData(@"gr[ae]y\s\S+?[\s\p{P}]", RegexOptions.None, null, true)]
        [InlineData(@"[\s\p{P}]", RegexOptions.None, null, true)]
        [InlineData(@"[\p{P}\d]", RegexOptions.None, null, true)]
        [InlineData(@"[^aeiou]", RegexOptions.None, null, true)]
        [InlineData(@"(\w)\1", RegexOptions.None, null, true)]
        [InlineData(@"[^\p{Ll}\p{Lu}\p{Lt}\p{Lo}\p{Nd}\p{Pc}\p{Lm}] ", RegexOptions.None, null, true)]
        [InlineData(@"[^a-zA-Z_0-9]", RegexOptions.None, null, true)]
        [InlineData(@"\P{Nd}", RegexOptions.None, null, true)]
        [InlineData(@"(\(?\d{3}\)?[\s-])?", RegexOptions.None, null, true)]
        [InlineData(@"^(\(?\d{3}\)?[\s-])?\d{3}-\d{4}$", RegexOptions.None, null, true)]
        [InlineData(@"[0-9]", RegexOptions.None, null, true)]
        [InlineData(@"\p{Nd}", RegexOptions.None, null, true)]
        [InlineData(@"\b(\S+)\s?", RegexOptions.None, null, true)]
        [InlineData(@"[^ \f\n\r\t\v]", RegexOptions.None, null, true)]
        [InlineData(@"[^\f\n\r\t\v\x85\p{Z}]", RegexOptions.None, null, true)]
        [InlineData(@"(\s|$)", RegexOptions.None, null, true)]
        [InlineData(@"\b\w+(e)?s(\s|$)", RegexOptions.None, null, true)]
        [InlineData(@"[ \f\n\r\t\v]", RegexOptions.None, null, true)]
        [InlineData(@"(\W){1,2}", RegexOptions.None, null, true)]
        [InlineData(@"(\w+)", RegexOptions.None, null, true)]
        [InlineData(@"\b", RegexOptions.None, null, true)]
        [InlineData(@"\b(\w+)(\W){1,2}", RegexOptions.None, null, true)]
        [InlineData(@"(?>(\w)\1+).\b", RegexOptions.None, null, true)]
        [InlineData(@"(\b(\w+)\W+)+", RegexOptions.None, null, true)]
        [InlineData(@"\p{Sc}*(\s?\d+[.,]?\d*)\p{Sc}*", RegexOptions.None, null, true)]
        [InlineData(@"p{Sc}*(?<amount>\s?\d+[.,]?\d*)\p{Sc}*", RegexOptions.None, null, true)]
        [InlineData(@"^(\w+\s?)+$", RegexOptions.None, null, true)]
        [InlineData(@"(?ix) d \w+ \s", RegexOptions.None, null, true)]
        [InlineData(@"\bthe\w*\b", RegexOptions.None, null, true)]
        [InlineData(@"\b(?i:t)he\w*\b", RegexOptions.None, null, true)]
        [InlineData(@"^(\w+)\s(\d+)$", RegexOptions.None, null, true)]
        [InlineData(@"^(\w+)\s(\d+)\r*$", RegexOptions.Multiline, null, true)]
        [InlineData(@"(?m)^(\w+)\s(\d+)\r*$", RegexOptions.Multiline, null, true)]
        [InlineData(@"(?s)^.+", RegexOptions.None, null, true)]
        [InlineData(@"\b(\d{2}-)*(?(1)\d{7}|\d{3}-\d{2}-\d{4})\b", RegexOptions.None, null, true)]
        [InlineData(@"\b\(?((\w+),?\s?)+[\.!?]\)?", RegexOptions.None, null, true)]
        [InlineData(@"(?n)\b\(?((?>\w+),?\s?)+[\.!?]\)?", RegexOptions.None, null, true)]
        [InlineData(@"\b\(?(?n:(?>\w+),?\s?)+[\.!?]\)?", RegexOptions.None, null, true)]
        [InlineData(@"\b\(?((?>\w+),?\s?)+[\.!?]\)?", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData(@"(?x)\b \(? ( (?>\w+) ,?\s? )+  [\.!?] \)? # Matches an entire sentence.", RegexOptions.None, null, true)]
        [InlineData(@"\bb\w+\s", RegexOptions.RightToLeft, null, true)]
        [InlineData(@"(?<=\d{1,2}\s)\w+,?\s\d{4}", RegexOptions.RightToLeft, null, true)]
        [InlineData(@"\b(\w+\s*)+", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"((a+)(\1) ?)+", RegexOptions.ECMAScript, null, true)]
        [InlineData(@"\b(D\w+)\s(d\w+)\b", RegexOptions.None, null, true)]
        [InlineData(@"\b(D\w+)(?ixn) \s (d\w+) \b", RegexOptions.None, null, true)]
        [InlineData(@"\b((?# case-sensitive comparison)D\w+)\s((?#case-insensitive comparison)d\w+)\b", RegexOptions.None, null, true)]
        [InlineData(@"\b\(?((?>\w+),?\s?)+[\.!?]\)?", RegexOptions.None, null, true)]
        [InlineData(@"\b(?<n2>\d{2}-)*(?(n2)\d{7}|\d{3}-\d{2}-\d{4})\b", RegexOptions.None, null, true)]
        [InlineData(@"\b(\d{2}-\d{7}|\d{3}-\d{2}-\d{4})\b", RegexOptions.None, null, true)]
        [InlineData(@"\bgr(a|e)y\b", RegexOptions.None, null, true)]
        [InlineData(@"\b91*9*\b", RegexOptions.None, null, true)]
        [InlineData(@"\ban+\w*?\b", RegexOptions.None, null, true)]
        [InlineData(@"\ban?\b", RegexOptions.None, null, true)]
        [InlineData(@"\b\d+\,\d{3}\b", RegexOptions.None, null, true)]
        [InlineData(@"\b\d{2,}\b\D+", RegexOptions.None, null, true)]
        [InlineData(@"(00\s){2,4}", RegexOptions.None, null, true)]
        [InlineData(@"\b\w*?oo\w*?\b", RegexOptions.None, null, true)]
        [InlineData(@"\b\w+?\b", RegexOptions.None, null, true)]
        [InlineData(@"^\s*(System.)??Console.Write(Line)??\(??", RegexOptions.None, null, true)]
        [InlineData(@"(System.)??", RegexOptions.None, null, true)]
        [InlineData(@"\b(\w{3,}?\.){2}?\w{3,}?\b", RegexOptions.None, null, true)]
        [InlineData(@"\b[A-Z](\w*?\s*?){1,10}[.!?]", RegexOptions.None, null, true)]
        [InlineData(@"b.*([0-9]{4})\b", RegexOptions.None, null, true)]
        [InlineData(@"\b.*?([0-9]{4})\b", RegexOptions.None, null, true)]
        [InlineData(@"(a?)*", RegexOptions.None, null, true)]
        [InlineData(@"(a\1|(?(1)\1)){0,2}", RegexOptions.None, null, true)]
        [InlineData(@"(a\1|(?(1)\1)){2}", RegexOptions.None, null, true)]
        [InlineData(@"(?<char>\w)\k<char>", RegexOptions.None, null, true)]
        [InlineData(@"(?<2>\w)\k<2>", RegexOptions.None, null, true)]
        [InlineData(@"(?<1>a)(?<1>\1b)*", RegexOptions.None, null, true)]
        [InlineData(@"\b(\p{Lu}{2})(\d{2})?(\p{Lu}{2})\b", RegexOptions.None, null, true)]
        [InlineData(@"\bgr[ae]y\b", RegexOptions.None, null, true)]
        [InlineData(@"\b((?# case sensitive comparison)D\w+)\s(?ixn)((?#case insensitive comparison)d\w+)\b", RegexOptions.None, null, true)]
        [InlineData(@"\{\d+(,-*\d+)*(\:\w{1,4}?)*\}(?x) # Looks for a composite format item.", RegexOptions.None, null, true)]
        // Negative tests
        [InlineData(@"cat([a-\d]*)dog", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"\k<1", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"(?')", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"(?<)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"(?)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"(?>", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?<!", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?<=", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?!", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?=", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?imn )", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?imn", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?:", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?'cat'", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?'", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"[^", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[cat", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[^cat", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"\p{", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"\p{cat", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"\k<cat", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"\p{cat}", RegexOptions.None, RegexParseError.UnknownUnicodeProperty, true)]
        [InlineData(@"\P{cat", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"\P{cat}", RegexOptions.None, RegexParseError.UnknownUnicodeProperty, true)]
        [InlineData(@"(", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?<cat>", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"\P{", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"\k<>", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"(?(", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?()|", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"?(a|b)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"?((a)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"?((a)a", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"?((a)a|", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"?((a)a|b", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"?(a)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"[a", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"?(a:b)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"(?(?", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(cat", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?(cat)|", RegexOptions.None, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"foo(?<0>bar)", RegexOptions.None, RegexParseError.CapnumNotZero, true)]
        [InlineData(@"foo(?'0'bar)", RegexOptions.None, RegexParseError.CapnumNotZero, true)]
        [InlineData(@"foo(?<1bar)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"foo(?'1bar)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"\p{klsak", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"(?c:cat)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(??e:cat)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"[a-f-[]]+", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"[A-[]+", RegexOptions.None, RegexParseError.UnterminatedBracket, true)]
        [InlineData(@"(?(?e))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?a)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?r:cat)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"\x2", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"(cat) (?#cat)    \s+ (?#followed by 1 or more whitespace", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnterminatedComment, true)]
        [InlineData(@"cat(?(?afdcat)dog)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"cat(?(?<cat>cat)dog)", RegexOptions.None, RegexParseError.AlternationCantCapture, true)]
        [InlineData(@"cat(?(?'cat'cat)dog)", RegexOptions.None, RegexParseError.AlternationCantCapture, true)]
        [InlineData(@"cat(?(?#COMMENT)cat)", RegexOptions.None, RegexParseError.AlternationCantHaveComment, true)]
        [InlineData(@"cat(?<>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"cat(?<dog<>)_*>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"cat(?<dog >)_*>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"cat(?<dog!>)_*>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"cat(?<dog)_*>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"cat(?<1dog>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"cat(?<0>dog)", RegexOptions.None, RegexParseError.CapnumNotZero, true)]
        [InlineData(@"([5-\D]*)dog", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"cat([6-\s]*)dog", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"cat([c-\S]*)", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"cat([7-\w]*)", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"cat([a-\W]*)dog", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"([f-\p{Lu}]\w*)\s([\p{Lu}]\w*)", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"(cat) (?#cat)    \s+ (?#followed by 1 or more whitespace", RegexOptions.None, RegexParseError.UnterminatedComment, true)]
        [InlineData(@"([1-\P{Ll}][\p{Ll}]*)\s([\P{Ll}][\p{Ll}]*)", RegexOptions.None, RegexParseError.BadClassInCharRange, true)]
        [InlineData(@"[\P]", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"([\pcat])", RegexOptions.None, RegexParseError.MalformedSlashP, true)]
        [InlineData(@"([\Pcat])", RegexOptions.None, RegexParseError.MalformedSlashP, true)]
        [InlineData(@"(\p{", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"(\p{Ll", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"(cat)([\o]*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedEscape, true)]
        [InlineData(@"[\p]", RegexOptions.None, RegexParseError.IncompleteSlashP, true)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\kcat", RegexOptions.None, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<cat2>", RegexOptions.None, RegexParseError.UndefinedNameRef, true)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<8>cat", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"^[abcd]{1}?*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]*+$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]+*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]?*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]*?+$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]+?*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]{1,}?*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]??*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]+{0,5}$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]?{0,5}$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"\ua", RegexOptions.None, RegexParseError.TooFewHex, true)]
        [InlineData(@"^[abcd]*{0,5}$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]{0,16}?*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"^[abcd]{1,}*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<8>cat", RegexOptions.ECMAScript, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k8", RegexOptions.None, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k8", RegexOptions.ECMAScript, RegexParseError.MalformedNameRef, true)]
        [InlineData(@"(cat)(\7)", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"(cat)\s+(?<2147483648>dog)", RegexOptions.None, RegexParseError.CaptureGroupOutOfRange, true)]
        [InlineData(@"(cat)\s+(?<21474836481097>dog)", RegexOptions.None, RegexParseError.CaptureGroupOutOfRange, true)]
        [InlineData(@"^[abcd]{1}*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"(cat)(\c*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"(cat)(\c *)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"(cat)(\c?*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"(cat)(\c`*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, true)]
        [InlineData(@"(cat)(\c\|*)(dog)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, true)]
        [InlineData(@"^[abcd]{0,16}*$", RegexOptions.None, RegexParseError.NestedQuantify, true)]
        [InlineData(@"(cat)\c", RegexOptions.None, RegexParseError.MissingControl, true)]
        // Basic
        [InlineData("a{2147483648}", RegexOptions.None, RegexParseError.CaptureGroupOutOfRange, false)]
        [InlineData("a{2147483648,}", RegexOptions.None, RegexParseError.CaptureGroupOutOfRange, false)]
        [InlineData("a{0,2147483647}", RegexOptions.None, null, false)]
        [InlineData("a{0,2147483648}", RegexOptions.None, RegexParseError.CaptureGroupOutOfRange, false)]
        // Deep recursion
        [InlineData(@"@""((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((
(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((""", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        // \d, \D, \s, \S, \w, \W, \P, \p inside character range
        [InlineData(@"cat([a-\d]*)dog", RegexOptions.None, RegexParseError.BadClassInCharRange, false)]
        [InlineData(@"([5-\D]*)dog", RegexOptions.None, RegexParseError.BadClassInCharRange, false)]
        [InlineData(@"cat([6-\s]*)dog", RegexOptions.None, RegexParseError.BadClassInCharRange, false)]
        [InlineData(@"cat([c-\S]*)", RegexOptions.None, RegexParseError.BadClassInCharRange, false)]
        [InlineData(@"cat([7-\w]*)", RegexOptions.None, RegexParseError.BadClassInCharRange, false)]
        [InlineData(@"cat([a-\W]*)dog", RegexOptions.None, RegexParseError.BadClassInCharRange, false)]
        [InlineData(@"([f-\p{Lu}]\w*)\s([\p{Lu}]\w*)", RegexOptions.None, RegexParseError.BadClassInCharRange, false)]
        [InlineData(@"([1-\P{Ll}][\p{Ll}]*)\s([\P{Ll}][\p{Ll}]*)", RegexOptions.None, RegexParseError.BadClassInCharRange, false)]
        [InlineData(@"[\p]", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        [InlineData(@"[\P]", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        [InlineData(@"([\pcat])", RegexOptions.None, RegexParseError.MalformedSlashP, false)]
        [InlineData(@"([\Pcat])", RegexOptions.None, RegexParseError.MalformedSlashP, false)]
        [InlineData(@"(\p{", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        [InlineData(@"(\p{Ll", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        // \x, \u, \a, \b, \e, \f, \n, \r, \t, \v, \c, inside character range
        [InlineData(@"(cat)([\o]*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedEscape, false)]
        // Use < in a group
        [InlineData(@"cat(?<0>dog)", RegexOptions.None, RegexParseError.CapnumNotZero, false)]
        [InlineData(@"cat(?<1dog>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData(@"cat(?<dog)_*>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData(@"cat(?<dog!>)_*>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData(@"cat(?<dog >)_*>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData(@"cat(?<dog<>)_*>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData(@"cat(?<>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData(@"(?<cat>cat)\w+(?<dog-16>dog)", RegexOptions.None, RegexParseError.UndefinedBackref, false)]
        [InlineData(@"(?<cat>cat)\w+(?<dog-1uosn>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData(@"(?<cat>cat)\w+(?<dog-catdog>dog)", RegexOptions.None, RegexParseError.UndefinedNameRef, false)]
        [InlineData(@"(?<cat>cat)\w+(?<dog-()*!@>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        // Use (? in a group
        [InlineData("cat(?(?#COMMENT)cat)", RegexOptions.None, RegexParseError.AlternationCantHaveComment, false)]
        [InlineData("cat(?(?'cat'cat)dog)", RegexOptions.None, RegexParseError.AlternationCantCapture, false)]
        [InlineData("cat(?(?<cat>cat)dog)", RegexOptions.None, RegexParseError.AlternationCantCapture, false)]
        [InlineData("cat(?(?afdcat)dog)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        // Pattern whitespace
        [InlineData(@"(cat) (?#cat)    \s+ (?#followed by 1 or more whitespace", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnterminatedComment, false)]
        [InlineData(@"(cat) (?#cat)    \s+ (?#followed by 1 or more whitespace", RegexOptions.None, RegexParseError.UnterminatedComment, false)]
        // Back reference
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\kcat", RegexOptions.None, RegexParseError.MalformedNameRef, false)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<cat2>", RegexOptions.None, RegexParseError.UndefinedNameRef, false)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<8>cat", RegexOptions.None, RegexParseError.UndefinedBackref, false)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k<8>cat", RegexOptions.ECMAScript, RegexParseError.UndefinedBackref, false)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k8", RegexOptions.None, RegexParseError.MalformedNameRef, false)]
        [InlineData(@"(?<cat>cat)\s+(?<dog>dog)\k8", RegexOptions.ECMAScript, RegexParseError.MalformedNameRef, false)]
        // Octal, decimal
        [InlineData(@"(cat)(\7)", RegexOptions.None, RegexParseError.UndefinedBackref, false)]
        [InlineData(@"(cat)\s+(?<2147483648>dog)", RegexOptions.None, RegexParseError.CaptureGroupOutOfRange, false)]
        [InlineData(@"(cat)\s+(?<21474836481097>dog)", RegexOptions.None, RegexParseError.CaptureGroupOutOfRange, false)]
        // Scan control
        [InlineData(@"(cat)(\c*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, false)]
        [InlineData(@"(cat)\c", RegexOptions.None, RegexParseError.MissingControl, false)]
        [InlineData(@"(cat)(\c *)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, false)]
        [InlineData(@"(cat)(\c?*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, false)]
        [InlineData("(cat)(\\c\0*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, false)]
        [InlineData(@"(cat)(\c`*)(dog)", RegexOptions.None, RegexParseError.UnrecognizedControl, false)]
        [InlineData(@"(cat)(\c\|*)(dog)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, false)]
        [InlineData(@"(cat)(\c\[*)(dog)", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        // Nested quantifiers
        [InlineData("^[abcd]{0,16}*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]{1,}*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]{1}*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]{0,16}?*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]{1,}?*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]{1}?*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]*+$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]+*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]?*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]*?+$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]+?*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]??*$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]*{0,5}$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]+{0,5}$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        [InlineData("^[abcd]?{0,5}$", RegexOptions.None, RegexParseError.NestedQuantify, false)]
        // Invalid character escapes
        [InlineData(@"\u", RegexOptions.None, RegexParseError.TooFewHex, false)]
        [InlineData(@"\ua", RegexOptions.None, RegexParseError.TooFewHex, false)]
        [InlineData(@"\u0", RegexOptions.None, RegexParseError.TooFewHex, false)]
        [InlineData(@"\x", RegexOptions.None, RegexParseError.TooFewHex, false)]
        [InlineData(@"\x2", RegexOptions.None, RegexParseError.TooFewHex, false)]
        // Invalid character class
        [InlineData("[", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[]", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[a", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[^", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[cat", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[^cat", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[a-", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData(@"\p{", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        [InlineData(@"\p{cat", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        [InlineData(@"\p{cat}", RegexOptions.None, RegexParseError.UnknownUnicodeProperty, false)]
        [InlineData(@"\P{", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        [InlineData(@"\P{cat", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        [InlineData(@"\P{cat}", RegexOptions.None, RegexParseError.UnknownUnicodeProperty, false)]
        // Invalid grouping constructs
        [InlineData("(", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(?<", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(?<cat>", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?'cat'", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?:", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?imn", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(?imn )", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(?=", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?!", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?<=", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?<!", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?>", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?>-", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, false)]
        [InlineData("(?<)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData("(?')", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData(@"\1", RegexOptions.None, RegexParseError.UndefinedBackref, false)]
        [InlineData(@"\k", RegexOptions.None, RegexParseError.MalformedNameRef, false)]
        [InlineData(@"\k<1", RegexOptions.None, RegexParseError.UnrecognizedEscape, false)]
        [InlineData(@"\k<cat", RegexOptions.None, RegexParseError.UnrecognizedEscape, false)]
        [InlineData(@"\k<>", RegexOptions.None, RegexParseError.UnrecognizedEscape, false)]
        // Invalid alternation constructs
        [InlineData("(?(", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?()|", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?(cat", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        [InlineData("(?(cat)|", RegexOptions.None, RegexParseError.NotEnoughParentheses, false)]
        // Regex with 0 numeric names
        [InlineData("foo(?<0>bar)", RegexOptions.None, RegexParseError.CapnumNotZero, false)]
        [InlineData("foo(?'0'bar)", RegexOptions.None, RegexParseError.CapnumNotZero, false)]
        // Regex without closing >
        [InlineData("foo(?<1bar)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        [InlineData("foo(?'1bar)", RegexOptions.None, RegexParseError.InvalidGroupName, false)]
        // Misc
        [InlineData(@"\p{klsak", RegexOptions.None, RegexParseError.IncompleteSlashP, false)]
        [InlineData("(?r:cat)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(?c:cat)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(??e:cat)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        // Character class subtraction
        [InlineData("[a-f-[]]+", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        //// Not character class substraction
        [InlineData("[A-[]+", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        // Invalid testgroup
        [InlineData("(?(?e))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(?(?a)", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(?(?", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("?(a)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, false)]
        [InlineData("?(a|b)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, false)]
        [InlineData("?((a)", RegexOptions.None, RegexParseError.QuantifyAfterNothing, false)]
        [InlineData("?((a)a", RegexOptions.None, RegexParseError.QuantifyAfterNothing, false)]
        [InlineData("?((a)a|", RegexOptions.None, RegexParseError.QuantifyAfterNothing, false)]
        [InlineData("?((a)a|b", RegexOptions.None, RegexParseError.QuantifyAfterNothing, false)]
        // Testgroup with options
        [InlineData(")", RegexOptions.None, RegexParseError.TooManyParentheses, false)]
        [InlineData("())", RegexOptions.None, RegexParseError.TooManyParentheses, false)]
        [InlineData("[a-z-[aeiuo]", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[a-z-[aeiuo", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[a-z-[b]", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[a-z-[b", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("[b-a]", RegexOptions.None, RegexParseError.ReversedCharRange, false)]
        [InlineData(@"[a-c]{2,1}", RegexOptions.None, RegexParseError.IllegalRange, false)]
        [InlineData(@"\d{2147483648}", RegexOptions.None, RegexParseError.CaptureGroupOutOfRange, false)]
        [InlineData("[a-z-[b][", RegexOptions.None, RegexParseError.UnterminatedBracket, false)]
        [InlineData("(?()|||||)", RegexOptions.None, RegexParseError.TooManyAlternates, false)]
        public void Parse(string pattern, RegexOptions options, object errorObj, bool runSubTreeTests)
        {
            RegexParseError? error = (RegexParseError?)errorObj;

            // Parse the main tree and if parsing fails check if the supplied error matches.
            ParseTree(pattern, options, error);

            if (runSubTreeTests)
            {
                // Assert that only ArgumentException might be thrown during parsing.
                ParseSubTrees(pattern, options);
            }
        }

        [Theory]
        [SkipOnTargetFramework(TargetFrameworkMonikers.NetFramework, "fixes not ported to netfx RegexParser")]
        // OutOfMemoryException
        [InlineData("a{2147483647}", RegexOptions.None, null, false)]
        [InlineData("a{2147483647,}", RegexOptions.None, null, false)]
        [InlineData(@"(?(?N))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?i))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?I))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?M))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?s))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?S))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?x))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?X))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"(?(?n))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(" (?(?n))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData(@"(?(?m))", RegexOptions.None, RegexParseError.UnrecognizedGrouping, true)]
        // IndexOutOfRangeException
        [InlineData("(?<-", RegexOptions.None, RegexParseError.UnrecognizedGrouping, false)]
        [InlineData("(?<-", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData(@"^[^<>]*(((?'Open'<)[^<>]*)+((?'Close-Open'>)[^<>]*)+)*(?(Open)(?!))$", RegexOptions.None, null, true)]
        [InlineData(@"((?'Close-Open'>)[^<>]*)+", RegexOptions.None, RegexParseError.UndefinedNameRef, true)]
        [InlineData(@"(((?'Open'<)[^<>]*)+((?'Close-Open'>)[^<>]*)+)*", RegexOptions.None, null, true)]
        [InlineData(@"(?'Close-Open'>)", RegexOptions.None, RegexParseError.UndefinedNameRef, true)]
        [InlineData("(?<a-00>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a>)()(?<-0>)(?<-1>)(?<-2>)(?<-3>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("()(?<a>)(?<-0>)(?<-1>)(?<-2>)(?<-3>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("()()(?<-0>)(?<-1>)(?<-2>)(?<-3>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("(?<a>)(?<b>)(?<-1>)(?<-2>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<-4>)(?<4>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<4>)(?<-4>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a>)(?<-a>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<-a>)(?<a>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a-0>", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData("(?<a-0>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a-0 >)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<a- 0 >)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<a- 0>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<-1>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("()(?<-1>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<-1>)()", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<-00>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a-", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?<a-0", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?<a-0)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<a>)(?<b>)(?<-0>)(?<-1>)(?<-2>)(?<-3>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)()()", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)()(?", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)()(?<a>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)(?<a>)()", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)(?<a>)(?", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("(?<-0>)(?<-1>)(?<-2>)(?<-3>)(?<a>)(?<b>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.UndefinedBackref, true)]
        [InlineData("(?<a-0>)(?<b-a>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a-0>)(?<-a>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<a-a>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<-0>)", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<-0 >)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<- 0 >)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<- 0>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<a-0')", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?'a-0>)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?'-0')", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?'a-0')", RegexOptions.IgnorePatternWhitespace, null, true)]
        [InlineData("(?<-0", RegexOptions.IgnorePatternWhitespace, RegexParseError.UnrecognizedGrouping, true)]
        [InlineData("(?<-0)", RegexOptions.IgnorePatternWhitespace, RegexParseError.InvalidGroupName, true)]
        [InlineData("(?<-0>", RegexOptions.IgnorePatternWhitespace, RegexParseError.NotEnoughParentheses, true)]
        [InlineData(@"(?<cat>cat)\w+(?<dog-()*!@>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"(?<cat>cat)\w+(?<dog-catdog>dog)", RegexOptions.None, RegexParseError.UndefinedNameRef, true)]
        [InlineData(@"(?<cat>cat)\w+(?<dog-1uosn>dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        [InlineData(@"(?<cat>cat)\w+(?<dog-16>dog)", RegexOptions.None, RegexParseError.UndefinedBackref, true)]
        [InlineData(@"cat(?<->dog)", RegexOptions.None, RegexParseError.InvalidGroupName, true)]
        public void Parse_NotNetFramework(string pattern, RegexOptions options, object error, bool runSubTreeTests)
        {
            Parse(pattern, options, error, runSubTreeTests);
        }

        private static void ParseSubTrees(string pattern, RegexOptions options)
        {
            // Trim the input from the right and make sure tree invariants hold
            for (int i = pattern.Length - 1; i > 0; i--)
            {
                ParseSubTree(pattern.Substring(0, i), options);
            }

            // Trim the input from the left and make sure tree invariants hold
            for (int i = 1; i < pattern.Length; i++)
            {
                ParseSubTree(pattern.Substring(i), options);
            }

            // Skip middles
            for (int i = 1; i < pattern.Length; i++)
            {
                ParseSubTree(pattern.Substring(0, i) + pattern.Substring(i + 1), options);
            }
        }

        private static void ParseTree(string pattern, RegexOptions options, RegexParseError? error)
        {
            if (error != null)
            {
                Throws(error.Value, () => new Regex(pattern, options));
                return;
            }

            // Nothing to assert here without having access to internals.
            new Regex(pattern, options);
        }

        private static void ParseSubTree(string pattern, RegexOptions options)
        {
            try
            {
                new Regex(pattern, options);
            }
            catch (ArgumentException)
            {
                // We are fine with ArgumentExceptions being thrown during sub expression parsing.
            }
        }

        /// <summary>
        /// Checks if action throws either a RegexParseException or an ArgumentException depending on the
        /// environment and the supplied error.
        /// </summary>
        /// <param name="error">The expected parse error</param>
        /// <param name="action">The action to invoke.</param>
        private static void Throws(RegexParseError error, Action action)
        {
            // If no specific error is supplied, or we are running on full framework where RegexParseException
            // doesn't exist or we are running on uapaot where reflection is blocked we expect an ArgumentException.
            if (PlatformDetection.IsNetNative || PlatformDetection.IsFullFramework)
            {
                Assert.ThrowsAny<ArgumentException>(action);
                return;
            }

            try
            {
                action();
            }
            catch (Exception e)
            {
                // We use reflection to check if the exception is an internal RegexParseException
                // and extract its error property and compare with the given one.
                if (e.GetType() == s_parseExceptionType)
                {
                    RegexParseError regexParseError = (RegexParseError)s_parseErrorField.GetValue(e);

                    // Success if provided error matches.
                    if (error == regexParseError)
                        return;

                    throw new XunitException($"Expected RegexParseException with error: ({error}) -> Actual error: {regexParseError})");
                }

                throw new XunitException($"Expected RegexParseException -> Actual: ({e.GetType()})");
            }

            throw new XunitException($"Expected RegexParseException with error: ({error}) -> Actual: No exception thrown");
        }
    }
}
