//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.Diagnostics.TraceSource.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- DEBUG ASSERTION FAILED ----.
        /// </summary>
        internal static string DebugAssertBanner {
            get {
                return ResourceManager.GetString("DebugAssertBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Assert Long Message ----.
        /// </summary>
        internal static string DebugAssertLongMessage {
            get {
                return ResourceManager.GetString("DebugAssertLongMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- Assert Short Message ----.
        /// </summary>
        internal static string DebugAssertShortMessage {
            get {
                return ResourceManager.GetString("DebugAssertShortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion Failed: Cancel=Debug, OK=Continue.
        /// </summary>
        internal static string DebugAssertTitle {
            get {
                return ResourceManager.GetString("DebugAssertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred writing trace output to log file &apos;{0}&apos;. {1}.
        /// </summary>
        internal static string ExceptionOccurred {
            get {
                return ResourceManager.GetString("ExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IndentSize property must be non-negative..
        /// </summary>
        internal static string IndentSize {
            get {
                return ResourceManager.GetString("IndentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument {0} cannot be null or zero-length..
        /// </summary>
        internal static string InvalidNullEmptyArgument {
            get {
                return ResourceManager.GetString("InvalidNullEmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only TraceListeners can be added to a TraceListenerCollection..
        /// </summary>
        internal static string MustAddListener {
            get {
                return ResourceManager.GetString("MustAddListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTL_False.
        /// </summary>
        internal static string RTL {
            get {
                return ResourceManager.GetString("RTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail:.
        /// </summary>
        internal static string TraceListenerFail {
            get {
                return ResourceManager.GetString("TraceListenerFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IndentSize property must be non-negative..
        /// </summary>
        internal static string TraceListenerIndentSize {
            get {
                return ResourceManager.GetString("TraceListenerIndentSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Level must be set to a value in the enumeration TraceLevel..
        /// </summary>
        internal static string TraceSwitchInvalidLevel {
            get {
                return ResourceManager.GetString("TraceSwitchInvalidLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to set {0} to a value that is too high.  Setting level to TraceLevel.Verbose.
        /// </summary>
        internal static string TraceSwitchLevelTooHigh {
            get {
                return ResourceManager.GetString("TraceSwitchLevelTooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempted to set {0} to a value that is too low.  Setting level to TraceLevel.Off.
        /// </summary>
        internal static string TraceSwitchLevelTooLow {
            get {
                return ResourceManager.GetString("TraceSwitchLevelTooLow", resourceCulture);
            }
        }
    }
}
