SET( REALPATH_SUPPORTS_NONEXISTENT_FILES_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( SSCANF_SUPPORT_ll_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( SSCANF_CANNOT_HANDLE_MISSING_EXPONENT_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_LARGE_SNPRINTF_SUPPORT_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_SCHED_GET_PRIORITY_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_WORKING_GETTIMEOFDAY_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_WORKING_CLOCK_GETTIME_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_CLOCK_MONOTONIC_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_MMAP_DEV_ZERO_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( MMAP_IGNORES_HINT_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( MMAP_DOESNOT_ALLOW_REMAP_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( ONE_SHARED_MAPPING_PER_FILEREGION_PER_PROCESS_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( PTHREAD_CREATE_MODIFIES_ERRNO_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( SEM_INIT_MODIFIES_ERRNO_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_COMPATIBLE_ACOS_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_COMPATIBLE_ASIN_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_COMPATIBLE_POW_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_VALID_NEGATIVE_INF_POW_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_VALID_POSITIVE_INF_POW_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_COMPATIBLE_ATAN2_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_COMPATIBLE_LOG_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_COMPATIBLE_LOG10_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( UNGETC_NOT_RETURN_EOF_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAS_POSIX_SEMAPHORES_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( GETPWUID_R_SETS_ERRNO_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( FILE_OPS_CHECK_FERROR_OF_PREVIOUS_CALL_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HAVE_SHM_OPEN_THAT_WORKS_WELL_ENOUGH_WITH_MMAP_EXITCODE 
     1
     CACHE STRING "Result from TRY_RUN" FORCE)

