//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specified file length was too large for the file system..
        /// </summary>
        internal static string ArgumentOutOfRange_FileLengthTooBig
        {
            get
            {
                return ResourceManager.GetString("ArgumentOutOfRange_FileLengthTooBig", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified buffer size is too large. FileSystemWatcher cannot allocate {0} bytes for the internal buffer..
        /// </summary>
        internal static string BufferSizeTooLarge
        {
            get
            {
                return ResourceManager.GetString("BufferSizeTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Too many changes at once in directory:{0}..
        /// </summary>
        internal static string FSW_BufferOverflow
        {
            get
            {
                return ResourceManager.GetString("FSW_BufferOverflow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error reading the {0} directory..
        /// </summary>
        internal static string FSW_IOError
        {
            get
            {
                return ResourceManager.GetString("FSW_IOError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The directory name {0} is invalid..
        /// </summary>
        internal static string InvalidDirName
        {
            get
            {
                return ResourceManager.GetString("InvalidDirName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The value of argument &apos;{0}&apos; ({1}) is invalid for Enum type &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidEnumArgument
        {
            get
            {
                return ResourceManager.GetString("InvalidEnumArgument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; already exists..
        /// </summary>
        internal static string IO_FileExists_Name
        {
            get
            {
                return ResourceManager.GetString("IO_FileExists_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to find the specified file..
        /// </summary>
        internal static string IO_FileNotFound
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find file &apos;{0}&apos;..
        /// </summary>
        internal static string IO_FileNotFound_FileName
        {
            get
            {
                return ResourceManager.GetString("IO_FileNotFound_FileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path..
        /// </summary>
        internal static string IO_PathNotFound_NoPathName
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_NoPathName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path &apos;{0}&apos;..
        /// </summary>
        internal static string IO_PathNotFound_Path
        {
            get
            {
                return ResourceManager.GetString("IO_PathNotFound_Path", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters..
        /// </summary>
        internal static string IO_PathTooLong
        {
            get
            {
                return ResourceManager.GetString("IO_PathTooLong", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file &apos;{0}&apos; because it is being used by another process..
        /// </summary>
        internal static string IO_SharingViolation_File
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_File", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The process cannot access the file because it is being used by another process..
        /// </summary>
        internal static string IO_SharingViolation_NoFileName
        {
            get
            {
                return ResourceManager.GetString("IO_SharingViolation_NoFileName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot access a closed file..
        /// </summary>
        internal static string ObjectDisposed_FileClosed
        {
            get
            {
                return ResourceManager.GetString("ObjectDisposed_FileClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access to the path is denied..
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_NoPathName
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_NoPathName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access to the path &apos;{0}&apos; is denied..
        /// </summary>
        internal static string UnauthorizedAccess_IODenied_Path
        {
            get
            {
                return ResourceManager.GetString("UnauthorizedAccess_IODenied_Path", resourceCulture);
            }
        }
    }
}
