# macOS legs
parameters:
  # Required: value to specify if the job is comming from an official build to run extra steps and sign binaries
  #   Default: false
  isOfficialBuild: false
  # Required: value to specify if the full test matrix should be tested
  #   Default: false
  fullMatrix: false
  # Optional: value to scope the tests.
  #   Default: empty
  testScope: ''

jobs:
- template: corefx-base.yml
  parameters:
    isOfficialBuild: ${{ parameters.isOfficialBuild }}
    testScope: ${{ parameters.testScope }}
    targetOS: OSX
    jobs:

    # Legs with Helix testing
    - job: MacOS
      displayName: MacOS
      strategy:
        matrix:
          ${{ if eq(parameters.fullMatrix, 'false') }}:
            x64_Debug:
              _BuildConfig: Debug
              _architecture: x64
              _framework: netcoreapp
              _helixQueues: $(macOSQueues)

          ${{ if eq(parameters.fullMatrix, 'true') }}:
            x64_Release:
              _BuildConfig: Release
              _architecture: x64
              _framework: netcoreapp
              _helixQueues: $(macOSQueues)
              _publishTests: true

      pool:
        name: Hosted macOS

      preBuildSteps:
        - script: |
            brew install pkgconfig openssl
            ln -s /usr/local/opt/openssl/lib/pkgconfig/libcrypto.pc /usr/local/lib/pkgconfig/
            ln -s /usr/local/opt/openssl/lib/pkgconfig/libssl.pc /usr/local/lib/pkgconfig/
            ln -s /usr/local/opt/openssl/lib/pkgconfig/openssl.pc /usr/local/lib/pkgconfig/
          displayName: Install Build Dependencies
      
      submitToHelix: true

      variables:
        - ${{ if eq(parameters.fullMatrix, 'false') }}:
          - macOSQueues: OSX.1013.Amd64.Open

        - ${{ if eq(parameters.fullMatrix, 'true') }}:
          - macOSQueues: OSX.1013.Amd64.Open+OSX.1014.Amd64.Open
