# macOS legs
parameters:
  # Required: value to specify if the job is comming from an official build to run extra steps and sign binaries
  #   Default: false
  isOfficialBuild: false
  # Required: value to specify if the build is comming from an outerloop pipeline.
  #   Default: false
  isOuterloopBuild: false
  # Required: value to specify if the build is comming from a code coverage pipeline.
  #   Default: false
  isCodeCoverageBuild: false

jobs:

- template: corefx-base.yml
  parameters:
    isOfficialBuild: ${{ parameters.isOfficialBuild }}
    isCodeCoverageBuild: ${{ parameters.isCodeCoverageBuild }}
    ${{ if or(eq(parameters.isOuterloopBuild, 'true'), eq(parameters.isCodeCoverageBuild, 'true'), eq(parameters.isOfficialBuild, 'true')) }}:
      runOuterloop: true

    targetOS: OSX
    jobs:

    # Legs with Helix testing
    - job: MacOS
      displayName: MacOS
      strategy:
        matrix:
          ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            x64_Debug:
              _BuildConfig: Debug
              _architecture: x64
              _framework: netcoreapp
              _helixQueues: $(macOSQueues)

          ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            x64_Release:
              _BuildConfig: Release
              _architecture: x64
              _framework: netcoreapp
              _helixQueues: $(macOSQueues)
              _publishTests: true

      pool:
        name: Hosted Mac Internal Sierra

      preBuildSteps:
        - script: |
            brew install pkgconfig openssl
            ln -s /usr/local/opt/openssl/lib/pkgconfig/libcrypto.pc /usr/local/lib/pkgconfig/
            ln -s /usr/local/opt/openssl/lib/pkgconfig/libssl.pc /usr/local/lib/pkgconfig/
            ln -s /usr/local/opt/openssl/lib/pkgconfig/openssl.pc /usr/local/lib/pkgconfig/
          displayName: Install Build Dependencies
      
      submitToHelix: true

      variables:
        - ${{ if eq(parameters.isOfficialBuild, 'false') }}:
          - macOSQueues: OSX.1012.Amd64.Open+OSX.1013.Amd64.Open

        - ${{ if eq(parameters.isOfficialBuild, 'true') }}:
          - macOSQueues: OSX.1012.Amd64+OSX.1013.Amd64+OSX.1014.Amd64
        
        - ${{ if eq(parameters.isCodeCoverageBuild, 'true') }}:
          - macOSQueues: OSX.1014.Amd64
