# Linux legs
jobs:

# Legs with Helix testing
- template: corefx-base.yml
  parameters:
    name: MacOS
    displayName: MacOS
    strategy:
      matrix:
        x64_Debug:
          _configuration: Debug
          _architecture: x64
          framework: netcoreapp
          helixQueues: $(macOSQueues)

    pool:
      name: Hosted Mac Internal Sierra

    targetOS: OSX

    preBuildSteps:
      - script: |
          brew install pkgconfig openssl
          ln -s /usr/local/opt/openssl/lib/pkgconfig/libcrypto.pc /usr/local/lib/pkgconfig/
          ln -s /usr/local/opt/openssl/lib/pkgconfig/libssl.pc /usr/local/lib/pkgconfig/
          ln -s /usr/local/opt/openssl/lib/pkgconfig/openssl.pc /usr/local/lib/pkgconfig/
        displayName: Install Build Dependencies
