# macOS legs
parameters:
  # Required: value to specify if the job is comming from an official build to run extra steps and sign binaries
  #   Default: false
  isOfficialBuild: false

jobs:

- template: corefx-base.yml
  parameters:
    isOfficialBuild: ${{ parameters.isOfficialBuild }}
    targetOS: OSX
    jobs:

    # Legs with Helix testing
    - job: MacOS
      displayName: MacOS
      strategy:
        matrix:
          ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            x64_Debug:
              _configuration: Debug
              _architecture: x64
              _framework: netcoreapp
              _helixQueues: $(macOSQueues)

          ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            x64_Release:
              _configuration: Release
              _architecture: x64
              _framework: netcoreapp
              _helixQueues: $(macOSQueues)

      pool:
        name: Hosted Mac Internal Sierra

      preBuildSteps:
        - script: |
            brew install pkgconfig openssl
            ln -s /usr/local/opt/openssl/lib/pkgconfig/libcrypto.pc /usr/local/lib/pkgconfig/
            ln -s /usr/local/opt/openssl/lib/pkgconfig/libssl.pc /usr/local/lib/pkgconfig/
            ln -s /usr/local/opt/openssl/lib/pkgconfig/openssl.pc /usr/local/lib/pkgconfig/
          displayName: Install Build Dependencies
      
      submitToHelix: true

      variables:
        - _skipTests: true
        - _outerloop: ${{ parameters.isOfficialBuild }}

        - ${{ if eq(parameters.isOfficialBuild, 'false') }}:
          - macOSQueues: OSX.1012.Amd64.Open+OSX.1013.Amd64.Open

        - ${{ if eq(parameters.isOfficialBuild, 'true') }}:
          - macOSQueues: OSX.1012.Amd64+OSX.1013.Amd64+OSX.1014.Amd64
