trigger: none

variables:
  - name: _isOfficialBuild
    value: ${{ and(ne(variables['System.TeamProject'], 'public'), notIn(variables['Build.Reason'], 'PullRequest')) }}
  - name: _fullMatrix
    value: ${{ notIn(variables['Build.Reason'], 'PullRequest') }}

resources:
  containers:
  - container: rhel7_container
    image: microsoft/dotnet-buildtools-prereqs:rhel7_prereqs_2

  - container: ubuntu_1604_arm64_cross_container
    image: microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921

  - container: alpine_36_container
    image: microsoft/dotnet-buildtools-prereqs:alpine-3.6-WithNode-f4d3fe3-20181213005010

jobs:
  # Windows outerloop legs
  - ${{ if endsWith(variables['Build.DefinitionName'], 'windows') }}:
    - template: /eng/pipelines/windows.yml
      parameters:
        isOfficialBuild: $(_isOfficialBuild)
        fullMatrix: $(_fullMatrix)
        isOuterloopBuild: true

  # Linux outerloop legs
  - ${{ if endsWith(variables['Build.DefinitionName'], 'linux') }}:
    - template: /eng/pipelines/linux.yml
      parameters:
        isOfficialBuild: $(_isOfficialBuild)
        fullMatrix: $(_fullMatrix)
        isOuterloopBuild: true

  # MacOS outerloop legs
  - ${{ if endsWith(variables['Build.DefinitionName'], 'osx') }}:
    - template: /eng/pipelines/macos.yml
      parameters:
        isOfficialBuild: $(_isOfficialBuild)
        fullMatrix: $(_fullMatrix)
        isOuterloopBuild: true