trigger: none

schedules:
- cron: "0 3 * * *"
  displayName: Outerloop scheduled build
  branches:
    include:
    - master
    - release/3.0

resources:
  containers:
  - container: centos7_container
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-f39df28-20191023143754

  - container: centos6_container
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-6-f39df28-20191023143802

  - container: alpine_39_container
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.9-WithNode-0fc54a3-20190918214015

  - container: alpine_37_arm64_container
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-cross-arm64-alpine-406629a-20191023143847

  - container: ubuntu_1604_arm64_cross_container
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-cross-arm64-cfdd435-20191023143847

  - container: ubuntu_1604_arm_cross_container
    image: mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-16.04-cross-14.04-23cacb0-20191023143847

stages:
  # Windows outerloop legs
  - ${{ if or(endsWith(variables['Build.DefinitionName'], 'windows'), endsWith(variables['Build.DefinitionName'], 'outerloop')) }}:
    - template: /eng/pipelines/windows.yml
      parameters:
        isOfficialBuild: ${{ and(ne(variables['System.TeamProject'], 'public'), notIn(variables['Build.Reason'], 'PullRequest')) }}
        fullMatrix: ${{ notIn(variables['Build.Reason'], 'PullRequest') }}
        testScope: outerloop

  # Linux outerloop legs
  - ${{ if or(endsWith(variables['Build.DefinitionName'], 'linux'), endsWith(variables['Build.DefinitionName'], 'outerloop')) }}:
    - template: /eng/pipelines/linux.yml
      parameters:
        isOfficialBuild: ${{ and(ne(variables['System.TeamProject'], 'public'), notIn(variables['Build.Reason'], 'PullRequest')) }}
        fullMatrix: ${{ notIn(variables['Build.Reason'], 'PullRequest') }}
        testScope: outerloop

  # MacOS outerloop legs
  - ${{ if or(endsWith(variables['Build.DefinitionName'], 'osx'), endsWith(variables['Build.DefinitionName'], 'outerloop')) }}:
    - template: /eng/pipelines/macos.yml
      parameters:
        isOfficialBuild: ${{ and(ne(variables['System.TeamProject'], 'public'), notIn(variables['Build.Reason'], 'PullRequest')) }}
        fullMatrix: ${{ notIn(variables['Build.Reason'], 'PullRequest') }}
        testScope: outerloop
