# RedHat 6 leg
parameters:
  # Required: value to specify if the job is comming from an official build to run extra steps and sign binaries
  #   Default: false
  isOfficialBuild: false
  # Required: value to specify if the full test matrix should be tested
  #   Default: false
  fullMatrix: false
  # Optional: value to scope the tests.
  #   Default: empty
  testScope: ''

jobs:
- template: corefx-base.yml
  parameters:
    isOfficialBuild: ${{ parameters.isOfficialBuild }}
    testScope: ${{ parameters.testScope }}
    targetOS: Linux
    jobs:

    - job: RedHat6
      strategy:
        matrix:
          x64_Release:
            _BuildConfig: Release
            _architecture: x64
            _framework: netcoreapp
            _buildExtraArguments: /p:RuntimeOS=rhel.6 /p:PortableBuild=false
            _dockerContainer: rhel6_container
            _helixQueues: $(redhatHelixQueue)

      pool:
        name: Hosted Ubuntu 1604

      container: $[ variables['_dockerContainer'] ]
      buildExtraArguments: $(_buildExtraArguments)
      submitToHelix: true

      variables:
        - redhatHelixQueue: RedHat.6.Amd64.Open
