trigger: none

pool:
  name: Hosted Ubuntu 1604

container: mcr.microsoft.com/dotnet/core/sdk:3.0.100-alpine

variables:
  httpStressProject: src/System.Net.Http/tests/StressTests/HttpStress/

steps:
- checkout: self
  clean: true
  fetchDepth: 0
  lfs: false

- task: CmdLine@2
  displayName: Build Corefx
  inputs:
    script: |
      ./build.sh -ci -c $(BUILD_CONFIGURATION)

- task: CmdLine@2
  displayName: Run HttpStress
  inputs:
    targetType: 'inline'
    script: |
      cd '$(Build.SourcesDirectory)/$(HttpStressProject)'
      # Load testhost sdk in environment
      . ./load-corefx-testhost.sh -c $(BUILD_CONFIGURATION) -b
      # Run the stress suite
      dotnet run -c $(BUILD_CONFIGURATION) -- $(HTTPSTRESS_ARGS)

- task: PublishBuildArtifacts@1
  displayName: Publish Logs
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/artifacts/log/$(BUILD_CONFIGURATION)'
    PublishLocation: Container
    ArtifactName: 'httpstress_$(Agent.Os)_$(Agent.JobName)'
  continueOnError: true
  condition: always()