# Windows legs
parameters:
  # Required: value to specify if the job is comming from an official build to run extra steps and sign binaries
  #   Default: false
  isOfficialBuild: false
  # Required: value to specify if the full test matrix should be tested
  #   Default: false
  fullMatrix: false
  # Optional: value to scope the tests.
  #   Default: empty
  testScope: ''

stages:
- stage: WindowsStage
  displayName: Windows
  dependsOn: []
  jobs:

  - template: corefx-base.yml
    parameters:
      isOfficialBuild: ${{ parameters.isOfficialBuild }}
      isInternalBuild: ${{ parameters.isInternalBuild }}
      testScope: ${{ parameters.testScope }}
      targetOS: Windows_NT
      jobs:

      # Legs with Helix testing
      - job: WindowsTest
        displayName: Build
        strategy:
          matrix:
            # PR CI Matrix
            ${{ if eq(parameters.fullMatrix, 'false') }}:
              x64_Debug:
                _BuildConfig: Debug
                _architecture: x64
                _framework: netcoreapp
                _helixQueues: $(netcoreappWindowsQueues)+$(nanoQueues)

              x86_Release:
                _BuildConfig: Release
                _architecture: x86
                _framework: netcoreapp
                _helixQueues: $(netcoreappWindowsQueues)

              NETFX_x86_Release:
                _BuildConfig: Release
                _architecture: x86
                _framework: netfx
                _helixQueues: $(uapNetfxQueues)

              UWP_CoreCLR_x64_Debug:
                _BuildConfig: Debug
                _architecture: x64
                _framework: uap
                _helixQueues: $(uapNetfxQueues)

            # Full test matrix
            ${{ if eq(parameters.fullMatrix, 'true') }}:
              x64_Release:
                _BuildConfig: Release
                _architecture: x64
                _framework: netcoreapp
                _helixQueues: $(netcoreappWindowsQueues)+$(nanoQueues)
                _publishTests: true

              x86_Release:
                _BuildConfig: Release
                _architecture: x86
                _framework: netcoreapp
                _helixQueues: $(netcoreappWindowsQueues)
                _publishTests: true

              NETFX_x86_Release:
                _BuildConfig: Release
                _architecture: x86
                _framework: netfx
                _helixQueues: $(uapNetfxQueues)
                _skipPublishPackages: true # In NETFX leg we don't produce packages

              NETFX_x64_Release:
                _BuildConfig: Release
                _architecture: x64
                _framework: netfx
                _helixQueues: $(uapNetfxQueues)
                _skipPublishPackages: true # In NETFX leg we don't produce packages

              UAP_x64_Release:
                _BuildConfig: Release
                _architecture: x64
                _framework: uap
                _helixQueues: $(uapNetfxQueues)
                _skipPublishPackages: true # In UWP we don't produce packages

              UAP_x86_Release:
                _BuildConfig: Release
                _architecture: x86
                _framework: uap
                _helixQueues: $(uapNetfxQueues)
                _skipPublishPackages: true # In UWP we don't produce packages

              arm64_Release:
                _BuildConfig: Release
                _architecture: arm64
                _framework: netcoreapp
                _helixQueues: $(windowsArmQueue)
                _publishTests: true

        pool:
          ${{ if ne(variables['System.TeamProject'], 'public') }}:
            name: NetCore1ESPool-Svc-Internal
            demands: ImageOverride -equals windows.vs2017.amd64
          ${{ if eq(variables['System.TeamProject'], 'public') }}:
            name: NetCore-Svc-Public
            demands: ImageOverride -equals windows.vs2017.amd64.Open

        submitToHelix: true
        # Temporarily until we increase the Windows ARM64 queue, https://github.com/dotnet/core-eng/issues/7756
        timeoutInMinutes: 180
        buildExtraArguments: /p:RuntimeOS=win10

        variables:
          - ${{ if eq(parameters.isInternalBuild, 'false') }}:
            - nanoQueues: "`(Windows.Nano.1809.Amd64.Open`)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504"
            - uapNetfxQueues: Windows.10.Amd64.ClientRS5.Open
            - windowsArmQueue: Windows.10.Arm64.Open

            - ${{ if eq(parameters.fullMatrix, 'false') }}:
              - netcoreappWindowsQueues: Windows.7.Amd64.Open+Windows.81.Amd64.Open+Windows.10.Amd64.Client21H1.Open

            - ${{ if eq(parameters.fullMatrix, 'true') }}:
              - netcoreappWindowsQueues: Windows.7.Amd64.Open+Windows.81.Amd64.Open+Windows.10.Amd64.ServerRS5.Open+Windows.10.Amd64.Client21H1.Open

          - ${{ else }}:
            - nanoQueues: "`(Windows.Nano.1809.Amd64`)windows.10.amd64.serverrs5@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64-08e8e40-20200107182504"
            - uapNetfxQueues: Windows.10.Amd64.ClientRS5
            - windowsArmQueue: Windows.10.Arm64

            - ${{ if eq(parameters.fullMatrix, 'false') }}:
              - netcoreappWindowsQueues: Windows.7.Amd64+Windows.81.Amd64+Windows.10.Amd64.Client21H1

            - ${{ if eq(parameters.fullMatrix, 'true') }}:
              - netcoreappWindowsQueues: Windows.7.Amd64+Windows.81.Amd64+Windows.10.Amd64.ServerRS5+Windows.10.Amd64.Client21H1

      # There is no point of running legs without outerloop tests, when in an outerloop build.
      - ${{ if and(ne(parameters.testScope, 'outerloop'), ne(parameters.testScope, 'all')) }}:
        # Packaging all configurations
        - job: AllConfigurations
          displayName: Packaging All Configurations
          strategy:
            matrix:
              ${{ if eq(parameters.fullMatrix, 'false') }}:
                x64_Debug:
                  _BuildConfig: Debug
                  _architecture: x64
                  _framework: allConfigurations
                  _helixQueues: $(allConfigurationsQueues)

              ${{ if eq(parameters.fullMatrix, 'true') }}:
                x64_Release:
                  _BuildConfig: Release
                  _architecture: x64
                  _framework: allConfigurations
                  _helixQueues: $(allConfigurationsQueues)

          pool:
            ${{ if ne(variables['System.TeamProject'], 'public') }}:
              name: NetCore1ESPool-Svc-Internal
              demands: ImageOverride -equals windows.vs2017.amd64
            ${{ if eq(variables['System.TeamProject'], 'public') }}:
              name: NetCore-Svc-Public
              demands: ImageOverride -equals windows.vs2017.amd64.Open

          submitToHelix: true
          buildExtraArguments: /p:RuntimeOS=win10

          variables:
            - ${{ if eq(parameters.isInternalBuild, 'false') }}:
              - allConfigurationsQueues: Windows.10.Amd64.ClientRS5.Open

            - ${{ else }}:
              - allConfigurationsQueues: Windows.10.Amd64.ClientRS5

          frameworkArg: -allConfigurations
          customBuildSteps:
            - script: build.cmd
                      -build
                      -configuration $(_BuildConfig)
                      -ci
                      -buildtests
                      -allconfigurations
                      -arch $(_architecture)
                      /p:RuntimeOS=win10
                      /p:ArchiveTests=Packages
                      $(_msbuildCommonParameters)
                      $(_InternalRuntimeDownloadArgs)
              displayName: Build Packages and Tests

        # Legs without HELIX testing
        - ${{ if eq(parameters.fullMatrix, 'true') }}:
          - job: WindowsNoTest
            displayName: Build
            strategy:
              matrix:
                arm_Release:
                  _BuildConfig: Release
                  _architecture: arm
                  _framework: netcoreapp

                UAP_arm_Release:
                  _BuildConfig: Release
                  _architecture: arm
                  _framework: uap
                  _skipPublishPackages: true # In UWP we don't produce packages
                  
            pool:
              ${{ if ne(variables['System.TeamProject'], 'public') }}:
                name: NetCore1ESPool-Svc-Internal
                demands: ImageOverride -equals windows.vs2017.amd64
              ${{ if eq(variables['System.TeamProject'], 'public') }}:
                name: NetCore-Svc-Public
                demands: ImageOverride -equals windows.vs2017.amd64.Open

            submitToHelix: false
            buildExtraArguments: /p:RuntimeOS=win10
