# Windows legs
parameters:
  # Required: value to specify if the job is comming from an official build to run extra steps and sign binaries
  #   Default: false
  isOfficialBuild: false
  # Required: value to specify if the build is comming from an outerloop pipeline.
  #   Default: false
  isOuterloopBuild: false

jobs:

- template: corefx-base.yml
  parameters:
    isOfficialBuild: ${{ parameters.isOfficialBuild }}
    targetOS: Windows_NT
    jobs:

    # Legs with Helix testing
    - job: WindowsTest
      displayName: Windows
      strategy:
        matrix:
          # PR CI Matrix
          ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            x64_Debug:
              _BuildConfig: Debug
              _architecture: x64
              _framework: netcoreapp
              _helixQueues: $(netcoreappWindowsQueues)+$(nanoQueues)

            x86_Release:
              _BuildConfig: Release
              _architecture: x86
              _framework: netcoreapp
              _helixQueues: $(netcoreappWindowsQueues)

            NETFX_x86_Release:
              _BuildConfig: Release
              _architecture: x86
              _framework: netfx
              _helixQueues: $(uapNetfxQueues)
              _skipPublishPackages: true # In NETFX leg we don't produce packages

            UWP_CoreCLR_x64_Debug:
              _BuildConfig: Debug
              _architecture: x64
              _framework: uap
              _helixQueues: $(uapNetfxQueues)
          
          # Official build LEGS with HELIX Testing
          ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            x64_Release:
              _BuildConfig: Release
              _architecture: x64
              _framework: netcoreapp
              _helixQueues: $(netcoreappWindowsQueues)+$(nanoQueues)
              _publishTests: true

            x86_Release:
              _BuildConfig: Release
              _architecture: x86
              _framework: netcoreapp
              _helixQueues: $(netcoreappWindowsQueues)
              _publishTests: true

            NETFX_x86_Release:
              _BuildConfig: Release
              _architecture: x86
              _framework: netfx
              _helixQueues: $(uapNetfxQueues)
              _skipPublishPackages: true # In NETFX leg we don't produce packages

            NETFX_x64_Release:
              _BuildConfig: Release
              _architecture: x64
              _framework: netfx
              _helixQueues: $(uapNetfxQueues)
              _skipPublishPackages: true # In NETFX leg we don't produce packages

            UAP_x64_Release:
              _BuildConfig: Release
              _architecture: x64
              _framework: uap
              _helixQueues: $(uapNetfxQueues)

            UAP_x86_Release:
              _BuildConfig: Release
              _architecture: x86
              _framework: uap
              _helixQueues: $(uapNetfxQueues)

            UAP_arm_Release:
              _BuildConfig: Release
              _architecture: arm
              _framework: uap
              _helixQueues: $(windowsArmQueue)

            UAPAOT_x86_Release:
              _BuildConfig: Release
              _architecture: x86
              _framework: uapaot
              _helixQueues: $(uapNetfxQueues)
              _restoreInternalTools: true

            UAPAOT_x64_Release:
              _BuildConfig: Release
              _architecture: x64
              _framework: uapaot
              _helixQueues: $(uapNetfxQueues)
              _restoreInternalTools: true

      pool:
        ${{ if eq(parameters.isOfficialBuild, 'true') }}:
          name: dotnet-internal-temp
        ${{ if eq(parameters.isOfficialBuild, 'false') }}:
          name: Hosted VS2017

      submitToHelix: true
      enableMicrobuild: ${{ parameters.isOfficialBuild }}
      buildExtraArguments: /p:RuntimeOS=win10

      variables:
        - _skipTests: true
        - _outerloop: ${{ parameters.isOfficialBuild }}
        - ${{ if eq(parameters.isOuterloopBuild, 'true') }}:
          - _outerloop: true

        - ${{ if eq(parameters.isOfficialBuild, 'false') }}:
          - netcoreappWindowsQueues: Windows.7.Amd64.Open+Windows.81.Amd64.Open+Windows.10.Amd64.ClientRS4.ES.Open
          - nanoQueues: Windows.10.Nano.Amd64.Open
          - uapNetfxQueues: Windows.10.Amd64.ClientRS5.Open

        - ${{ if eq(parameters.isOfficialBuild, 'true') }}:
          - netcoreappWindowsQueues: Windows.7.Amd64+Windows.81.Amd64+Windows.10.Amd64.Core+Windows.10.Amd64.ClientRS4
          - nanoQueues: Windows.10.Nano.Amd64
          - uapNetfxQueues: Windows.10.Amd64.ClientRS5
          - windowsArmQueue: Windows.10.Arm64

    # There is no point of running legs without outerloop tests, when in an outerloop build.
    - ${{ if eq(parameters.isOuterloopBuild, 'false') }}:
      # Packaging all configurations
      - job: AllConfigurations
        displayName: Packaging All Configurations
        strategy:
          matrix:
            # PR Validation Matrix
            ${{ if eq(parameters.isOfficialBuild, 'false') }}:
              x64_Debug:
                _BuildConfig: Debug
                _architecture: x64
                _framework: allConfigurations
                _helixQueues: $(allConfigurationsQueues)

            # Official Build Matrix
            ${{ if eq(parameters.isOfficialBuild, 'true') }}:
              x64_Release:
                _BuildConfig: Release
                _architecture: x64
                _framework: allConfigurations
                _helixQueues: $(allConfigurationsQueues)

        pool:
          ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            name: dotnet-internal-temp
          ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            name: Hosted VS2017

        submitToHelix: true
        # azure pipelines reporter only supports xunit results based tests.
        enableAzurePipelinesReporter: false
        enableMicrobuild: ${{ parameters.isOfficialBuild }}

        variables:
          - _outerloop: false
          - ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            - allConfigurationsQueues: Windows.10.Amd64.ClientRS4.Open
          - ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            - allConfigurationsQueues: Windows.10.Amd64.ClientRS4

        customBuildSteps:
          - script: build.cmd
                    -restore
                    -build
                    -configuration $(_BuildConfig)
                    -ci
                    -buildtests
                    -allconfigurations
                    -arch $(_architecture)
                    /p:RuntimeOS=win10
                    /p:ArchiveTests=Packages
                    $(_windowsOfficialBuildArguments)
                    $(_msbuildCommonParameters)
            displayName: Build Packages and Tests
          - ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            - script: build.cmd
                      -restore
                      -build
                      -configuration $(_BuildConfig)
                      -ci
                      -buildtests
                      -framework netstandard
                      -arch $(_architecture)
              displayName: Build Netstandard Test Suite

      # TODO: UAPAOT official builds should send to helix using continuation runner.
      # Legs without HELIX testing
      - job: WindowsNoTest
        displayName: Windows
        strategy:
          matrix:
            ${{ if eq(parameters.isOfficialBuild, 'false') }}:
              UWP_NETNative_x86_Release:
                _BuildConfig: Release
                _architecture: x86
                _framework: uapaot
                _restoreInternalTools: true

            ${{ if eq(parameters.isOfficialBuild, 'true') }}:
              arm_Release:
                _BuildConfig: Release
                _architecture: arm
                _framework: netcoreapp

              arm64_Release:
                _BuildConfig: Release
                _architecture: arm64
                _framework: netcoreapp

              UAPAOT_arm_Release:
                _BuildConfig: Release
                _architecture: arm
                _framework: uapaot
                _restoreInternalTools: true

              UAPAOT_arm64_Release:
                _BuildConfig: Release
                _architecture: arm64
                _framework: uapaot
                _restoreInternalTools: true

        pool:
          ${{ if eq(parameters.isOfficialBuild, 'true') }}:
            name: dotnet-internal-temp
          ${{ if eq(parameters.isOfficialBuild, 'false') }}:
            name: Hosted VS2017

        submitToHelix: false
        enableMicrobuild: ${{ parameters.isOfficialBuild }}
        buildExtraArguments: /p:RuntimeOS=win10

        variables:
          - _skipTests: true
          - _outerloop: ${{ parameters.isOfficialBuild }}
