// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Runtime.CompilerServices;
// Microsoft.CSharp
[assembly: TypeForwardedTo(typeof(Microsoft.CSharp.RuntimeBinder.Binder))]
// Microsoft.VisualBasic
[assembly: TypeForwardedTo(typeof(Microsoft.VisualBasic.Strings))]
// System.Collections
[assembly: TypeForwardedTo(typeof(System.Collections.Generic.List<>))]
// System.Collections.Concurrent
[assembly: TypeForwardedTo(typeof(System.Collections.Concurrent.ConcurrentDictionary<,>))]
// System.ComponentModel
[assembly: TypeForwardedTo(typeof(System.ComponentModel.CancelEventArgs))]
// System.ComponentModel.Annotations
[assembly: TypeForwardedTo(typeof(System.ComponentModel.DataAnnotations.ValidationResult))]
// System.ComponentModel.EventBasedAsync
[assembly: TypeForwardedTo(typeof(System.ComponentModel.AsyncCompletedEventArgs))]
// System.Diagnostics.Contracts
[assembly: TypeForwardedTo(typeof(System.Diagnostics.Contracts.Contract))]
// System.Diagnostics.Debug
[assembly: TypeForwardedTo(typeof(System.Diagnostics.Debug))]
// System.Diagnostics.Tools
[assembly: TypeForwardedTo(typeof(System.CodeDom.Compiler.GeneratedCodeAttribute))]
// System.Diagnostics.Tracing
[assembly: TypeForwardedTo(typeof(System.Diagnostics.Tracing.EventSource))]
// System.Dynamic.Runtime
[assembly: TypeForwardedTo(typeof(System.Dynamic.DynamicObject))]
// System.Globalization
[assembly: TypeForwardedTo(typeof(System.Globalization.CultureInfo))]
// System.IO
[assembly: TypeForwardedTo(typeof(System.IO.Stream))]
// System.IO.Compression
[assembly: TypeForwardedTo(typeof(System.IO.Compression.GZipStream))]
//  System.Linq
[assembly: TypeForwardedTo(typeof(System.Linq.Enumerable))]
//  System.Linq.Expressions
[assembly: TypeForwardedTo(typeof(System.Linq.Expressions.Expression))]
//  System.Linq.Parallel
[assembly: TypeForwardedTo(typeof(System.Linq.ParallelEnumerable))]
//  System.Linq.Queryable
[assembly: TypeForwardedTo(typeof(System.Linq.Queryable))]
//  System.Net.Http
[assembly: TypeForwardedTo(typeof(System.Net.Http.HttpClient))]
//  System.Net.Http.Rtc
//  not supported on desktop
//  System.Net.NetworkInformation
[assembly: TypeForwardedTo(typeof(System.Net.NetworkInformation.NetworkInterface))]
//  System.Net.Primitives
[assembly: TypeForwardedTo(typeof(System.Net.HttpStatusCode))]
//  System.Net.Requests
[assembly: TypeForwardedTo(typeof(System.Net.HttpWebRequest))]
//  System.ObjectModel
[assembly: TypeForwardedTo(typeof(System.ComponentModel.INotifyPropertyChanged))]
//  System.Reflection
[assembly: TypeForwardedTo(typeof(System.Reflection.MethodInfo))]
//  System.Reflection.Context
[assembly: TypeForwardedTo(typeof(System.Reflection.Context.CustomReflectionContext))]
//  System.Reflection.Extensions
[assembly: TypeForwardedTo(typeof(System.Reflection.InterfaceMapping))]
//  System.Reflection.Primitives
[assembly: TypeForwardedTo(typeof(System.Reflection.TypeAttributes))]
//  System.Resources.ResourceManager
[assembly: TypeForwardedTo(typeof(System.Resources.ResourceManager))]
//  System.Runtime
[assembly: TypeForwardedTo(typeof(string))]
//  System.Runtime.Extensions
[assembly: TypeForwardedTo(typeof(System.Environment))]
//  System.Runtime.InteropServices
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.DllImportAttribute))]
//  System.Runtime.InteropServices.WindowsRuntime
[assembly: TypeForwardedTo(typeof(System.Runtime.InteropServices.WindowsRuntime.ReadOnlyArrayAttribute))]
//  System.Runtime.Numerics
[assembly: TypeForwardedTo(typeof(System.Numerics.BigInteger))]
//  System.Runtime.Serialization.Json
[assembly: TypeForwardedTo(typeof(System.Runtime.Serialization.Json.DataContractJsonSerializer))]
//  System.Runtime.Serialization.Primitives
[assembly: TypeForwardedTo(typeof(System.Runtime.Serialization.DataContractAttribute))]
//  System.Runtime.Serialization.Xml
[assembly: TypeForwardedTo(typeof(System.Runtime.Serialization.DataContractSerializer))]
//  System.Runtime.WindowsRuntime
//  not supported on desktop
//  System.Runtime.WindowsRuntime.UI.Xaml
//  not supported on desktop
//  System.Security.Principal
[assembly: TypeForwardedTo(typeof(System.Security.Principal.IPrincipal))]
//  System.ServiceModel.Duplex
[assembly: TypeForwardedTo(typeof(System.ServiceModel.DuplexClientBase<>))]
//  System.ServiceModel.Http
[assembly: TypeForwardedTo(typeof(System.ServiceModel.BasicHttpBinding))]
//  System.ServiceModel.NetTcp
[assembly: TypeForwardedTo(typeof(System.ServiceModel.NetTcpBinding))]
//  System.ServiceModel.Primitives
[assembly: TypeForwardedTo(typeof(System.ServiceModel.ClientBase<>))]
//  System.ServiceModel.Security
[assembly: TypeForwardedTo(typeof(System.ServiceModel.Channels.LocalClientSecuritySettings))]
//  System.Text.Encoding
[assembly: TypeForwardedTo(typeof(System.Text.Encoding))]
//  System.Text.Encoding.Extensions
[assembly: TypeForwardedTo(typeof(System.Text.UTF8Encoding))]
//  System.Text.RegularExpressions
[assembly: TypeForwardedTo(typeof(System.Text.RegularExpressions.Regex))]
//  System.Threading
[assembly: TypeForwardedTo(typeof(System.Threading.Mutex))]
//  System.Threading.Tasks
[assembly: TypeForwardedTo(typeof(System.Threading.Tasks.Task))]
//  System.Threading.Tasks.Parallel
[assembly: TypeForwardedTo(typeof(System.Threading.Tasks.Parallel))]
//  System.Threading.Timer
[assembly: TypeForwardedTo(typeof(System.Threading.Timer))]
//  System.Xml.ReaderWriter
[assembly: TypeForwardedTo(typeof(System.Xml.XmlReader))]
//  System.Xml.XDocument
[assembly: TypeForwardedTo(typeof(System.Xml.Linq.XDocument))]
//  System.Xml.XmlSerializer
[assembly: TypeForwardedTo(typeof(System.Xml.Serialization.XmlSerializer))]
