// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace System.Reflection.Metadata
{
    public enum MetadataKind
    {
        /// <summary>
        /// CLI metadata.
        /// </summary>
        Ecma335,

        /// <summary>
        /// Windows Metadata.
        /// </summary>
        WindowsMetadata,

        /// <summary>
        /// Windows Metadata generated by managed compilers.
        /// </summary>
        ManagedWindowsMetadata,
    }
}
