// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Diagnostics;

namespace Microsoft.CSharp.RuntimeBinder.Syntax
{
    internal static class NameManager
    {
        private static readonly string[] s_predefinedNames = {
            ".ctor",
            "Finalize",
            ".cctor",
            "*",
            "?*",
            "#",
            "&",
            "[X\001",
            "[X\002",
            "[X\003",
            "[G\001",
            "[G\002",
            "[G\003",
            "Invoke",
            "Length",
            "Item",
            "$Item$",
            "Combine",
            "Remove",
            "op_Explicit",
            "op_Implicit",
            "op_UnaryPlus",
            "op_UnaryNegation",
            "op_OnesComplement",
            "op_Increment",
            "op_Decrement",
            "op_Addition",
            "op_Subtraction",
            "op_Multiply",
            "op_Division",
            "op_Modulus",
            "op_ExclusiveOr",
            "op_BitwiseAnd",
            "op_BitwiseOr",
            "op_LeftShift",
            "op_RightShift",
            "op_Equals",
            "op_Compare",
            "op_Equality",
            "op_Inequality",
            "op_GreaterThan",
            "op_LessThan",
            "op_GreaterThanOrEqual",
            "op_LessThanOrEqual",
            "op_True",
            "op_False",
            "op_LogicalNot",
            "Concat",
            "Add",
            "get_Length",
            "get_Chars",
            "CreateDelegate",
            "FixedElementField",
            "HasValue",
            "get_HasValue",
            "Value",
            "get_Value",
            "GetValueOrDefault",
            "?",
            "<?>",
            "Lambda",
            "Parameter",
            "Constant",
            "Convert",
            "ConvertChecked",
            "AddChecked",
            "Divide",
            "Modulo",
            "Multiply",
            "MultiplyChecked",
            "Subtract",
            "SubtractChecked",
            "And",
            "Or",
            "ExclusiveOr",
            "LeftShift",
            "RightShift",
            "AndAlso",
            "OrElse",
            "Equal",
            "NotEqual",
            "GreaterThanOrEqual",
            "GreaterThan",
            "LessThan",
            "LessThanOrEqual",
            "ArrayIndex",
            "Assign",
            "Condition",
            "Field",
            "Call",
            "New",
            "Quote",
            "ArrayLength",
            "UnaryPlus",
            "Negate",
            "NegateChecked",
            "Not",
            "NewArrayInit",
            "Property",
            "AddEventHandler",
            "RemoveEventHandler",
            "InvocationList",
            "GetOrCreateEventRegistrationTokenTable",
            /* Above here corresponds with PredefinedName enum */
            "true",
            "false",
            "null",
            "base",
            "this",
            "explicit",
            "implicit",
            "__arglist",
            "__makeref",
            "__reftype",
            "__refvalue",
            "as",
            "checked",
            "is",
            "typeof",
            "unchecked",
            "void",
            ""
        };

        internal static string GetPredefinedName(PredefinedName id)
        {
            Debug.Assert(id < PredefinedName.PN_COUNT);
            return s_predefinedNames[(int)id];
        }
    }
}
