// Do not edit this file manually it is auto-generated during the build based on the .resx file for this project.
namespace System
{
    internal static partial class SR
    {
#pragma warning disable 0414
        private const string s_resourcesName = "System.Collections.Specialized.resources"; // assembly Name + .resources
#pragma warning restore 0414

#if !DEBUGRESOURCES
        internal static string ArgumentNull_Key {
              get { return SR.GetResourceString("ArgumentNull_Key", null); }
        }
        internal static string Argument_AddingDuplicate {
              get { return SR.GetResourceString("Argument_AddingDuplicate", null); }
        }
        internal static string Argument_InvalidValue {
              get { return SR.GetResourceString("Argument_InvalidValue", null); }
        }
        internal static string ArgumentOutOfRange_NeedNonNegNum {
              get { return SR.GetResourceString("ArgumentOutOfRange_NeedNonNegNum", null); }
        }
        internal static string InvalidOperation_EnumFailedVersion {
              get { return SR.GetResourceString("InvalidOperation_EnumFailedVersion", null); }
        }
        internal static string InvalidOperation_EnumOpCantHappen {
              get { return SR.GetResourceString("InvalidOperation_EnumOpCantHappen", null); }
        }
        internal static string Arg_MultiRank {
              get { return SR.GetResourceString("Arg_MultiRank", null); }
        }
        internal static string Arg_InsufficientSpace {
              get { return SR.GetResourceString("Arg_InsufficientSpace", null); }
        }
        internal static string CollectionReadOnly {
              get { return SR.GetResourceString("CollectionReadOnly", null); }
        }
        internal static string BitVectorFull {
              get { return SR.GetResourceString("BitVectorFull", null); }
        }
        internal static string IndexOutOfRange {
              get { return SR.GetResourceString("IndexOutOfRange", null); }
        }
        internal static string OrderedDictionary_ReadOnly {
              get { return SR.GetResourceString("OrderedDictionary_ReadOnly", null); }
        }
        internal static string ArgumentNull_Array {
              get { return SR.GetResourceString("ArgumentNull_Array", null); }
        }
        internal static string Arg_ArrayPlusOffTooSmall {
              get { return SR.GetResourceString("Arg_ArrayPlusOffTooSmall", null); }
        }
        internal static string NotSupported_KeyCollectionSet {
              get { return SR.GetResourceString("NotSupported_KeyCollectionSet", null); }
        }
        internal static string NotSupported_ValueCollectionSet {
              get { return SR.GetResourceString("NotSupported_ValueCollectionSet", null); }
        }
#else
        internal static string ArgumentNull_Key {
              get { return SR.GetResourceString("ArgumentNull_Key", @"Key cannot be null."); }
        }
        internal static string Argument_AddingDuplicate {
              get { return SR.GetResourceString("Argument_AddingDuplicate", @"An entry with the same key already exists."); }
        }
        internal static string Argument_InvalidValue {
              get { return SR.GetResourceString("Argument_InvalidValue", @"Argument {0} should be larger than {1}."); }
        }
        internal static string ArgumentOutOfRange_NeedNonNegNum {
              get { return SR.GetResourceString("ArgumentOutOfRange_NeedNonNegNum", @"Index is less than zero."); }
        }
        internal static string InvalidOperation_EnumFailedVersion {
              get { return SR.GetResourceString("InvalidOperation_EnumFailedVersion", @"Collection was modified after the enumerator was instantiated."); }
        }
        internal static string InvalidOperation_EnumOpCantHappen {
              get { return SR.GetResourceString("InvalidOperation_EnumOpCantHappen", @"Enumerator is positioned before the first element or after the last element of the collection."); }
        }
        internal static string Arg_MultiRank {
              get { return SR.GetResourceString("Arg_MultiRank", @"Multi dimension array is not supported on this operation."); }
        }
        internal static string Arg_InsufficientSpace {
              get { return SR.GetResourceString("Arg_InsufficientSpace", @"Insufficient space in the target location to copy the information."); }
        }
        internal static string CollectionReadOnly {
              get { return SR.GetResourceString("CollectionReadOnly", @"Collection is read-only."); }
        }
        internal static string BitVectorFull {
              get { return SR.GetResourceString("BitVectorFull", @"Bit vector is full."); }
        }
        internal static string IndexOutOfRange {
              get { return SR.GetResourceString("IndexOutOfRange", @"Index {0} is out of range."); }
        }
        internal static string OrderedDictionary_ReadOnly {
              get { return SR.GetResourceString("OrderedDictionary_ReadOnly", @"The OrderedDictionary is read-only and cannot be modified."); }
        }
        internal static string ArgumentNull_Array {
              get { return SR.GetResourceString("ArgumentNull_Array", @"Array cannot be null."); }
        }
        internal static string Arg_ArrayPlusOffTooSmall {
              get { return SR.GetResourceString("Arg_ArrayPlusOffTooSmall", @"Destination array is not long enough to copy all the items in the collection. Check array index and length."); }
        }
        internal static string NotSupported_KeyCollectionSet {
              get { return SR.GetResourceString("NotSupported_KeyCollectionSet", @"Mutating a key collection derived from a dictionary is not allowed."); }
        }
        internal static string NotSupported_ValueCollectionSet {
              get { return SR.GetResourceString("NotSupported_ValueCollectionSet", @"Mutating a value collection derived from a dictionary is not allowed."); }
        }

#endif
    }
}
